# Canonical Correlation Analysis of 16S V1-V3 and V4 and metabolomics table with top VIPs

Date created: 1/29/2024

Notebook author: Yang Chen

Data analysis by: Britta de Pessemier, Yang Chen

In [1092]:
import biom
from biom import load_table
from biom.util import biom_open
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import CCA
from sklearn.preprocessing import StandardScaler
from skbio.stats.composition import clr
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx

In [1093]:
# Function to load BIOM table, sort rows by sum
def biom_to_df(biom_path):

    # Load BIOM table and convert to a DataFrame
    table = biom.load_table(biom_path)

    df = pd.DataFrame(table.matrix_data.toarray(),
                      index=table.ids(axis='observation'),
                      columns=table.ids(axis='sample'))
    
    
    # Sort rows by row sum in descending order
    df['row_sum'] = df.sum(axis=1)
    df = df.sort_values(by='row_sum', ascending=False)
    
    # Drop the 'row_sum' column before proceeding
    df = df.drop(columns=['row_sum'])

    # Transpose df
    df = df.T
    
    return df

In [1094]:
def save_as_biom(df: pd.DataFrame, output_path: str):
    """
    Save a pandas DataFrame as a BIOM table.

    Parameters:
    df (pd.DataFrame): The DataFrame to save.
    output_path (str): Path to the output BIOM file.
    """
    table = biom.table.Table(df.values, observation_ids=df.index, sample_ids=df.columns)
    with biom_open(output_path, 'w') as f:
        table.to_hdf5(f, "save biom")

In [1095]:
# Read in the metadata
metadata = pd.read_csv('../Metadata/metadata_final_18062024.tsv', sep='\t')
metadata

,SampleID,c_zone,visual_assessment_in_vivo_number_of_non_inflammatory_lesions_face,zone,sample_type,planned_study_day_of_visit,visual_assessment_in_vivo_number_of_inflammatory_lesions_face,day,subject_randomization_number,visual_assessment_in_vivo_number_of_non_inflammatory_lesions_cheek_right,...,inflammatory_lesions_face,noninflammatory_lesions_face,a,cohort,subject_randomization_id,class,subject_ID,subject_ID_CC,zone_CC,group
0,LAMI.RD308.D16.C1,C1,not applicable,Lesional,skin,Day 16,not applicable,16,308,not applicable,...,0,0,33.765638,acne,RD308,acne,PP_308,PP_308C1,Lesional_C1,Acne_L
1,LAMI.RD310.D21.C1,C1,72,Lesional,skin,Day 21,36,21,310,17,...,36,72,31.919478,acne,RD310,acne,PP_310,PP_310C1,Lesional_C1,Acne_L
2,LAMI.RD305.D21.C3,C3,69,Non-lesional,skin,Day 21,26,21,305,25,...,26,69,22.152503,acne,RD305,healthy,PP_305,PP_305C3,Non-lesional_C3,Acne_NL
3,LAMI.RD306.D18.C2,C2,not applicable,Lesional,skin,Day 18,not applicable,18,306,not applicable,...,0,0,27.397918,acne,RD306,acne,PP_306,PP_306C2,Lesional_C2,Acne_L
4,LAMI.RD306.D7.C2,C2,90,Lesional,skin,Day 7,13,7,306,23,...,13,90,28.819451,acne,RD306,acne,PP_306,PP_306C2,Lesional_C2,Acne_L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,LAMI.RD317.D21.C1,C1,77,Lesional,skin,Day 21,19,21,317,20,...,19,77,21.946648,acne,RD317,acne,PP_317,PP_317C1,Lesional_C1,Acne_L
262,LAMI.RD001.D0.C1,C1,not applicable,Non-lesional,skin,Day 0,not applicable,0,1,not applicable,...,0,0,26.344240,control,RD001,healthy,PP_1,PP_1C1,Non-lesional_C1,Healthy
263,LAMI.RD014.D14.C2,C2,not applicable,Non-lesional,skin,Day 14,not applicable,14,14,not applicable,...,0,0,16.359699,control,RD014,healthy,PP_14,PP_14C2,Non-lesional_C2,Healthy
264,LAMI.RD314.D0.C1,C1,55,Lesional,skin,Day 0,31,0,314,16,...,31,55,22.494605,acne,RD314,acne,PP_314,PP_314C1,Lesional_C1,Acne_L
265,LAMI.RD001.D14.C2,C2,not applicable,Non-lesional,skin,Day 14,not applicable,14,1,not applicable,...,0,0,20.676062,control,RD001,healthy,PP_1,PP_1C2,Non-lesional_C2,Healthy

In [1096]:
# skin_group = "Acne_L"
# skin_group = "Acne_NL"
skin_group = "Healthy"

In [1097]:
# Read in metabolomics table and set index
metaB_tbl = pd.read_csv('../Data/metabolomics/Run3_10252024/output/data_sample_10282024.csv')
metaB_tbl = metaB_tbl.set_index('SampleID')

# Read in VIP-filtered feature list
VIP_filtered = pd.read_csv('../Data/metabolomics/Run3_10252024/output/VIP_filtered_with_shortened_names.tsv', sep='\t')

# Get list of VIP feature IDs
vip_features = VIP_filtered['ID'].astype(str).unique().tolist()

# Extract the feature ID from each column name (assumes feature ID is before the first semicolon)
col_ids = [col.split(';')[0] for col in metaB_tbl.columns]

# Map original column names to their extracted feature IDs
col_map = dict(zip(metaB_tbl.columns, col_ids))

# Keep only columns where the extracted ID matches a VIP feature
cols_to_keep = [col for col, cid in col_map.items() if cid in vip_features]

# Subset the table to keep only those columns
metaB_tbl = metaB_tbl[cols_to_keep]

# Rename columns using Shortened_Compound_Name from VIP_filtered
# Create mapping of ID to Shortened_Compound_Name
name_map = dict(zip(VIP_filtered['ID'].astype(str), VIP_filtered['Shortened_Compound_Name']))

# Create a mapping from feature ID to shortened name, mz, and RT
VIP_filtered['ID'] = VIP_filtered['ID'].astype(str)  # Ensure IDs are strings
name_map = VIP_filtered.set_index('ID')['Shortened_Compound_Name'].to_dict()
mz_map = VIP_filtered.set_index('ID')['mz'].to_dict()
rt_map = VIP_filtered.set_index('ID')['RT'].to_dict()

# Build new column names
new_cols = []
for col in metaB_tbl.columns:
    feature_id = col.split(';')[0]  # Extract feature ID
    short_name = name_map.get(feature_id, feature_id)
    mz = mz_map.get(feature_id, 'NA')
    rt = rt_map.get(feature_id, 'NA')
    new_col_name = f"{short_name} (mz: {mz}, RT: {rt})"
    new_cols.append(new_col_name)

# Rename the columns
metaB_tbl.columns = new_cols

# View the result
metaB_tbl

,"Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Paracetamol (mz: 152.0704373, RT: 1.6221956)","Nicotine (mz: 163.1224157, RT: 0.634317)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","DL-Panthenol (mz: 206.1384472, RT: 1.1194918)",...,"(Iso)leucine (mz: 276.143683, RT: 0.6789317)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1323557)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","Nobiletin (mz: 403.138254, RT: 5.258404)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)"
SampleID,,,,,,,,,,,,,,,,,,,,,
LAMI.RD001.D0.C1,2987383.80,2025607.40,29574.6480,39859.7580,28277.594,0.00,970487.500,1942604.500,567510.060,1473068.10,...,62007.1100,12406.8260,611709.700,16778.838,0.0000,0.000,0.000,0.00,0.0000,125692.3300
LAMI.RD306.D9.C2,2051791.50,2260333.20,34466.4840,0.0000,253083.810,178911.47,1071868.200,3572847.500,672054.400,308019.97,...,153381.2700,20433.4900,437938.200,12865.390,0.0000,0.000,0.000,0.00,0.0000,10553.9270
LAMI.RD308.D2.C2,1121916.40,1669351.50,2905.5796,3065.1714,19280.236,0.00,750870.100,1618142.800,442653.660,286004.00,...,87817.2000,5348.9400,231525.840,14299.352,0.0000,0.000,0.000,0.00,3822.6377,4734.5693
LAMI.RD304.D11.C1,1818308.60,1434033.20,47379.2730,36750.4000,15391.807,0.00,595568.940,1605551.000,328151.120,299140.06,...,58588.9260,9403.6520,78491.530,0.000,5375.8525,11225.194,23546.951,99470.69,29824.6270,12473.0920
LAMI.RD304.D11.C2,1126503.20,706197.75,3460.0974,0.0000,15015.189,0.00,303845.300,865753.500,152392.720,191713.67,...,20153.3320,2286.2397,261996.800,15780.309,2691.0256,16378.752,34863.656,157503.92,44084.5860,40673.1100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LAMI.RD318.D9.C3,1173415.00,1250164.60,8613.8590,9787.1210,14712.559,0.00,579058.800,1380958.500,498893.780,236111.75,...,24563.9240,5144.6616,122958.260,56654.043,0.0000,0.000,0.000,0.00,0.0000,0.0000
LAMI.RD308.D9.C3,550094.94,687527.06,3163.9185,3076.9688,17934.553,0.00,281896.700,742416.600,262886.470,303509.40,...,24480.3900,0.0000,65659.700,21826.117,0.0000,0.000,0.000,0.00,0.0000,220846.1600
LAMI.RD319.D2.C2,602147.10,538412.94,4006.6484,0.0000,10556.326,0.00,255542.720,1194061.900,121803.890,5406879.00,...,35224.5800,0.0000,73231.560,19741.246,0.0000,0.000,0.000,0.00,0.0000,25695.0140
LAMI.RD319.D2.C3,171846.72,106901.95,0.0000,1407.5230,25369.129,0.00,59064.336,833009.000,23485.404,2838344.20,...,25342.2100,0.0000,55986.290,0.000,0.0000,0.000,0.000,0.00,0.0000,11039.7300
LAMI.RD318.D21.C2,400723.72,365100.34,4839.8540,0.0000,20615.168,0.00,185104.470,20027.605,116420.730,364993.20,...,6948.2324,0.0000,53308.617,18413.504,0.0000,0.000,0.000,0.00,0.0000,73266.4200

In [1098]:
# Read in 16S V1-V3 table
V1V3_biom_path = '../Data/16S/Tables/16S_V1-V3_Genus_collapsed_absolute.biom'
V1V3_tbl = biom_to_df(V1V3_biom_path)
# Extract the feature name after the last semicolon for each column
# V1V3_tbl.columns = V1V3_tbl.columns.str.split(';').str[-1].str.strip()
# # Sort columns by their sum in descending order
# V1V3_tbl = V1V3_tbl.loc[:, V1V3_tbl.sum().sort_values(ascending=False).index]


# Read in 16S V4 table
V4_biom_path = '../Data/16S/Tables/16S_V4_Genus_collapsed_absolute.biom'
V4_tbl = biom_to_df(V4_biom_path)

In [1099]:
V1V3_tbl

,g__Cutibacterium,g__uncultured,g__Staphylococcus,g__Streptococcus,g__Corynebacterium,g__Lawsonella,g__Veillonella,g__Micrococcus,g__Alloprevotella,g__Lactobacillus,...,g__Ramlibacter,g__Delftia,g__Lacibacter,g__Luteitalea,g__Pseudochrobactrum,g__Methylotenera,g__Fusicatenibacter,g__Ruminococcus,g__Lachnospira,g__Parabacteroides
LAMI.RD001.D0.C1,2362.0,0.0,94.0,292.0,175.0,91.0,33.0,37.0,18.0,1.0,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D0.C2,1808.0,2.0,158.0,374.0,352.0,120.0,36.0,52.0,27.0,165.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D14.C1,2234.0,2.0,83.0,240.0,492.0,253.0,19.0,30.0,30.0,60.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D14.C2,1761.0,0.0,137.0,446.0,456.0,151.0,69.0,16.0,100.0,26.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D28.C1,2367.0,11.0,118.0,293.0,365.0,217.0,34.0,22.0,38.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LAMI.RD319.D14.C1,1900.0,1846.0,8.0,0.0,6.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD319.D21.C3,1003.0,2741.0,11.0,1.0,4.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD319.D14.C2,2315.0,1410.0,8.0,0.0,9.0,27.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD319.D9.C1,1230.0,2491.0,13.0,1.0,3.0,31.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD319.D9.C2,2314.0,1411.0,8.0,0.0,14.0,20.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [1100]:
# Subset metaB_tbl rows where sample is in V1V3_tbl
metaB_V1V3_tbl = metaB_tbl[metaB_tbl.index.isin(V1V3_tbl.index)]

# Remove the 'group' column (only for VIP table)
# metaB_V1V3_tbl = metaB_V1V3_tbl.drop(columns=['group'])
metaB_V1V3_tbl.index.name = None
metaB_V1V3_tbl

,"Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Paracetamol (mz: 152.0704373, RT: 1.6221956)","Nicotine (mz: 163.1224157, RT: 0.634317)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","DL-Panthenol (mz: 206.1384472, RT: 1.1194918)",...,"(Iso)leucine (mz: 276.143683, RT: 0.6789317)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1323557)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","Nobiletin (mz: 403.138254, RT: 5.258404)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)"
LAMI.RD001.D0.C1,2987383.80,2025607.40,29574.6480,39859.7580,28277.594,0.00,970487.500,1942604.500,567510.060,1473068.10,...,62007.1100,12406.8260,611709.700,16778.8380,0.0000,0.000,0.000,0.00,0.000,125692.330
LAMI.RD306.D9.C2,2051791.50,2260333.20,34466.4840,0.0000,253083.810,178911.47,1071868.200,3572847.500,672054.400,308019.97,...,153381.2700,20433.4900,437938.200,12865.3900,0.0000,0.000,0.000,0.00,0.000,10553.927
LAMI.RD304.D11.C1,1818308.60,1434033.20,47379.2730,36750.4000,15391.807,0.00,595568.940,1605551.000,328151.120,299140.06,...,58588.9260,9403.6520,78491.530,0.0000,5375.8525,11225.194,23546.951,99470.69,29824.627,12473.092
LAMI.RD304.D11.C2,1126503.20,706197.75,3460.0974,0.0000,15015.189,0.00,303845.300,865753.500,152392.720,191713.67,...,20153.3320,2286.2397,261996.800,15780.3090,2691.0256,16378.752,34863.656,157503.92,44084.586,40673.110
LAMI.RD304.D0.C1,827466.30,778566.10,4547.2640,3345.8184,45187.030,0.00,293386.340,1321474.400,137201.390,705570.80,...,45193.9400,0.0000,427202.060,3228.1143,3431.0034,0.000,0.000,0.00,0.000,49464.902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LAMI.RD318.D9.C3,1173415.00,1250164.60,8613.8590,9787.1210,14712.559,0.00,579058.800,1380958.500,498893.780,236111.75,...,24563.9240,5144.6616,122958.260,56654.0430,0.0000,0.000,0.000,0.00,0.000,0.000
LAMI.RD308.D9.C3,550094.94,687527.06,3163.9185,3076.9688,17934.553,0.00,281896.700,742416.600,262886.470,303509.40,...,24480.3900,0.0000,65659.700,21826.1170,0.0000,0.000,0.000,0.00,0.000,220846.160
LAMI.RD319.D2.C2,602147.10,538412.94,4006.6484,0.0000,10556.326,0.00,255542.720,1194061.900,121803.890,5406879.00,...,35224.5800,0.0000,73231.560,19741.2460,0.0000,0.000,0.000,0.00,0.000,25695.014
LAMI.RD319.D2.C3,171846.72,106901.95,0.0000,1407.5230,25369.129,0.00,59064.336,833009.000,23485.404,2838344.20,...,25342.2100,0.0000,55986.290,0.0000,0.0000,0.000,0.000,0.00,0.000,11039.730
LAMI.RD318.D21.C2,400723.72,365100.34,4839.8540,0.0000,20615.168,0.00,185104.470,20027.605,116420.730,364993.20,...,6948.2324,0.0000,53308.617,18413.5040,0.0000,0.000,0.000,0.00,0.000,73266.420

In [1101]:
# Convert to relative abundance (row-wise normalization)
metaB_V1V3_tbl_relative = metaB_V1V3_tbl.div(metaB_V1V3_tbl.sum(axis=1), axis=0)
metaB_V1V3_tbl_relative

,"Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Paracetamol (mz: 152.0704373, RT: 1.6221956)","Nicotine (mz: 163.1224157, RT: 0.634317)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","DL-Panthenol (mz: 206.1384472, RT: 1.1194918)",...,"(Iso)leucine (mz: 276.143683, RT: 0.6789317)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1323557)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","Nobiletin (mz: 403.138254, RT: 5.258404)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)"
LAMI.RD001.D0.C1,0.265648,0.180123,0.002630,0.003544,0.002515,0.000000,0.086299,0.172743,0.050465,0.130990,...,0.005514,0.001103,0.054395,0.001492,0.000000,0.000000,0.000000,0.000000,0.000000,0.011177
LAMI.RD306.D9.C2,0.177092,0.195092,0.002975,0.000000,0.021844,0.015442,0.092514,0.308376,0.058006,0.026585,...,0.013238,0.001764,0.037799,0.001110,0.000000,0.000000,0.000000,0.000000,0.000000,0.000911
LAMI.RD304.D11.C1,0.269227,0.212329,0.007015,0.005441,0.002279,0.000000,0.088183,0.237725,0.048588,0.044292,...,0.008675,0.001392,0.011622,0.000000,0.000796,0.001662,0.003486,0.014728,0.004416,0.001847
LAMI.RD304.D11.C2,0.274761,0.172246,0.000844,0.000000,0.003662,0.000000,0.074110,0.211162,0.037169,0.046760,...,0.004916,0.000558,0.063903,0.003849,0.000656,0.003995,0.008503,0.038416,0.010752,0.009920
LAMI.RD304.D0.C1,0.172611,0.162410,0.000949,0.000698,0.009426,0.000000,0.061201,0.275662,0.028620,0.147184,...,0.009428,0.000000,0.089115,0.000673,0.000716,0.000000,0.000000,0.000000,0.000000,0.010318
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LAMI.RD318.D9.C3,0.210388,0.224149,0.001544,0.001755,0.002638,0.000000,0.103823,0.247600,0.089449,0.042334,...,0.004404,0.000922,0.022046,0.010158,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD308.D9.C3,0.139416,0.174247,0.000802,0.000780,0.004545,0.000000,0.071444,0.188158,0.066626,0.076921,...,0.006204,0.000000,0.016641,0.005532,0.000000,0.000000,0.000000,0.000000,0.000000,0.055971
LAMI.RD319.D2.C2,0.071895,0.064285,0.000478,0.000000,0.001260,0.000000,0.030511,0.142568,0.014543,0.645566,...,0.004206,0.000000,0.008744,0.002357,0.000000,0.000000,0.000000,0.000000,0.000000,0.003068
LAMI.RD319.D2.C3,0.040939,0.025467,0.000000,0.000335,0.006044,0.000000,0.014071,0.198447,0.005595,0.676175,...,0.006037,0.000000,0.013338,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002630
LAMI.RD318.D21.C2,0.238046,0.216884,0.002875,0.000000,0.012246,0.000000,0.109960,0.011897,0.069159,0.216821,...,0.004128,0.000000,0.031667,0.010938,0.000000,0.000000,0.000000,0.000000,0.000000,0.043523

In [1102]:
# Filter metadata for the correct group
filtered_metadata = metadata[metadata['group'] == skin_group]

# Normalize SampleID and index formatting
metaB_V1V3_tbl_relative.index = metaB_V1V3_tbl_relative.index.str.strip().str.upper()
filtered_metadata['SampleID'] = filtered_metadata['SampleID'].str.strip().str.upper()

# Filter metadata to only include matching SampleIDs
filtered_metadata = filtered_metadata[filtered_metadata['SampleID'].isin(metaB_V1V3_tbl_relative.index)]

# Subset the DataFrame
metaB_V1V3_tbl_relative = metaB_V1V3_tbl_relative.loc[filtered_metadata['SampleID']]

metaB_V1V3_tbl_relative

/var/folders/22/yck9vwx53w1c38tvj_c0_tz00000gn/T/ipykernel_3481/3342871550.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_metadata['SampleID'] = filtered_metadata['SampleID'].str.strip().str.upper()

,"Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Paracetamol (mz: 152.0704373, RT: 1.6221956)","Nicotine (mz: 163.1224157, RT: 0.634317)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","DL-Panthenol (mz: 206.1384472, RT: 1.1194918)",...,"(Iso)leucine (mz: 276.143683, RT: 0.6789317)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1323557)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","Nobiletin (mz: 403.138254, RT: 5.258404)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)"
LAMI.RD002.D14.C1,0.177464,0.159415,0.002228,0.000646,0.010071,0.000000,0.081174,0.334196,0.034301,0.069704,...,0.016729,0.000396,0.060050,0.001087,0.0,0.000000,0.008208,0.000000,0.019387,0.000000
LAMI.RD003.D14.C1,0.043985,0.036410,0.000000,0.000000,0.004719,0.000000,0.014899,0.085250,0.006927,0.790429,...,0.004982,0.000000,0.001511,0.000286,0.0,0.000000,0.000000,0.000000,0.000000,0.001695
LAMI.RD017.D0.C2,0.225856,0.195690,0.000000,0.000997,0.001983,0.002688,0.096634,0.287196,0.056365,0.033499,...,0.008864,0.000000,0.037747,0.003979,0.0,0.000000,0.000000,0.003933,0.000000,0.000581
LAMI.RD007.D14.C1,0.206929,0.171066,0.001356,0.000000,0.005920,0.010829,0.076215,0.302280,0.027798,0.095579,...,0.008078,0.000993,0.054766,0.003050,0.0,0.000000,0.000000,0.000000,0.000000,0.017369
LAMI.RD017.D28.C2,0.241377,0.257380,0.000284,0.000256,0.000982,0.010516,0.127992,0.205061,0.077467,0.012105,...,0.005975,0.002195,0.024483,0.003850,0.0,0.000000,0.000000,0.001510,0.000000,0.000335
LAMI.RD002.D28.C2,0.045730,0.024322,0.000070,0.000000,0.002893,0.001367,0.010188,0.086950,0.006321,0.810122,...,0.002050,0.000034,0.000179,0.001058,0.0,0.000000,0.000000,0.001187,0.000000,0.004675
LAMI.RD004.D0.C1,0.177376,0.094539,0.000904,0.001157,0.003262,0.019609,0.038629,0.277297,0.028480,0.262060,...,0.008955,0.000168,0.058771,0.000000,0.0,0.000000,0.000000,0.004322,0.000000,0.000000
LAMI.RD003.D28.C1,0.210181,0.108887,0.000000,0.000752,0.003702,0.000000,0.043909,0.165153,0.029659,0.380396,...,0.006914,0.000358,0.003779,0.003913,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD001.D14.C1,0.230963,0.232861,0.003391,0.002454,0.001484,0.000888,0.105728,0.195136,0.049886,0.035618,...,0.006185,0.003094,0.080559,0.000359,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD001.D28.C1,0.295443,0.196816,0.002237,0.003003,0.003460,0.000270,0.104208,0.208874,0.075193,0.021648,...,0.007380,0.005108,0.015558,0.001258,0.0,0.000000,0.000000,0.002090,0.000000,0.002443
LAMI.RD002.D14.C2,0.184455,0.137121,0.000931,0.000000,0.003968,0.000000,0.062494,0.448280,0.024075,0.050386,...,0.010070,0.000710,0.015327,0.001239,0.0,0.001133,0.007982,0.000000,0.018861,0.016739
LAMI.RD006.D28.C1,0.044553,0.024489,0.000119,0.000000,0.003613,0.002637,0.009993,0.087602,0.004667,0.815019,...,0.001525,0.000020,0.000434,0.000758,0.0,0.000000,0.000000,0.000664,0.000000,0.001095
LAMI.RD006.D14.C1,0.087079,0.037841,0.000000,0.000344,0.000427,0.008884,0.014522,0.052685,0.008457,0.779160,...,0.001562,0.000000,0.000313,0.001936,0.0,0.000000,0.000000,0.000000,0.000000,0.000541
LAMI.RD011.D28.C1,0.126626,0.087783,0.000000,0.000000,0.013217,0.001274,0.051032,0.467159,0.013833,0.187627,...,0.007781,0.000000,0.020018,0.002861,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD007.D14.C2,0.206547,0.168960,0.000429,0.000334,0.005719,0.014434,0.069950,0.353268,0.030642,0.098004,...,0.011326,0.000818,0.014396,0.000695,0.0,0.000000,0.000000,0.000000,0.000000,0.006568
LAMI.RD014.D28.C2,0.067922,0.045781,0.000378,0.000000,0.001327,0.000000,0.019330,0.153701,0.012512,0.647965,...,0.005379,0.000000,0.003661,0.004756,0.0,0.000000,0.000000,0.024438,0.000000,0.001311
LAMI.RD018.D0.C2,0.161313,0.159250,0.001568,0.007939,0.007427,0.021588,0.067975,0.296047,0.043221,0.100254,...,0.018767,0.000000,0.062964,0.001525,0.0,0.000000,0.002178,0.000000,0.000000,0.021104
LAMI.RD003.D0.C1,0.143309,0.097205,0.000577,0.000000,0.002926,0.000000,0.048682,0.513491,0.022081,0.127819,...,0.013517,0.000000,0.000000,0.003215,0.0,0.000000,0.000000,0.000000,0.000000,0.001357
LAMI.RD011.D14.C2,0.098061,0.082586,0.000550,0.000000,0.001354,0.000000,0.032164,0.120290,0.017096,0.622115,...,0.005693,0.000195,0.002874,0.000751,0.0,0.000000,0.000000,0.000000,0.000000,0.001931
LAMI.RD002.D0.C2,0.144926,0.149667,0.003131,0.001064,0.001344,0.000000,0.066196,0.162618,0.034111,0.386486,...,0.006045,0.000486,0.019747,0.000511,0.0,0.000000,0.000000,0.000000,0.000000,0.009600
LAMI.RD007.D0.C1,0.082689,0.053286,0.000071,0.000000,0.001261,0.007393,0.026169,0.127656,0.009976,0.644385,...,0.002582,0.000212,0.032503,0.001978,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD018.D28.C2,0.213679,0.223601,0.001944,0.000686,0.001629,0.004512,0.104973,0.234164,0.079786,0.034950,...,0.003189,0.002676,0.035418,0.007267,0.0,0.000000,0.000000,0.000000,0.000000,0.017818
LAMI.RD007.D28.C1,0.182298,0.152776,0.000000,0.000000,0.009969,0.008638,0.064433,0.226915,0.023081,0.077988,...,0.006204,0.000000,0.209593,0.002076,0.0,0.000000,0.000000,0.000000,0.000000,0.020231
LAMI.RD007.D28.C2,0.231895,0.184723,0.005339,0.000414,0.003776,0.015688,0.086177,0.247069,0.046920,0.059466,...,0.006896,0.000000,0.070455,0.002839,0.0,0.000000,0.000000,0.008954,0.000000,0.000000
LAMI.RD001.D0.C2,0.225045,0.160554,0.001287,0.001263,0.001349,0.000348,0.071860,0.168027,0.038263,0.236712,...,0.005661,0.001188,0.049936,0.000379,0.0,0.000000,0.000000,0.000000,0.000000,0.004045
LAMI.RD006.D0.C2,0.254878,0.191773,0.000862,0.001164,0.003612,0.057490,0.074009,0.253760,0.029962,0.083348,...,0.009282,0.000757,0.006822,0.003337,0.0,0.000000,0.000000,0.000000,0.000000,0.010109
LAMI.RD018.D0.C1,0.253247,0.203595,0.001172,0.001450,0.006066,0.032272,0.076093,0.246301,0.038094,0.045951,...,0.007959,0.001962,0.052010,0.003533,0.0,0.000000,0.003149,0.000000,0.000000,0.000000
LAMI.RD002.D0.C1,0.181416,0.143461,0.001248,0.003256,0.001565,0.000000,0.061702,0.132904,0.033109,0.381850,...,0.002898,0.000103,0.029987,0.001443,0.0,0.000000,0.000000,0.000000,0.000000,0.000725
LAMI.RD018.D28.C1,0.221158,0.231352,0.007184,0.000605,0.003766,0.003241,0.105802,0.226778,0.078211,0.043531,...,0.001682,0.001965,0.035994,0.005530,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD018.D14.C1,0.151879,0.076893,0.003165,0.000000,0.014513,0.015064,0.038263,0.489262,0.014213,0.109198,...,0.014290,0.000000,0.038498,0.001336,0.0,0.000000,0.000000,0.000000,0.000000,0.018942
LAMI.RD006.D14.C2,0.080630,0.052253,0.000496,0.001050,0.000623,0.004973,0.022194,0.063834,0.013500,0.745155,...,0.002312,0.000173,0.000633,0.002730,0.0,0.000000,0.000000,0.000458,0.000000,0.000268
LAMI.RD001.D28.C2,0.317870,0.198551,0.006032,0.003829,0.005223,0.000628,0.089775,0.205688,0.049229,0.023498,...,0.006721,0.003011,0.041083,0.001776,0.0,0.000000,0.000000,0.000000,0.000000,0.001790
LAMI.RD004.D28.C2,0.246397,0.109640,0.000000,0.000000,0.004873,0.047656,0.049982,0.281812,0.034234,0.098307,...,0.001965,0.000000,0.045287,0.000000,0.0,0.000000,0.000000,0.010320,0.000000,0.000000
LAMI.RD011.D0.C2,0.106911,0.102710,0.000000,0.000000,0.006828,0.000693,0.046251,0.337303,0.019839,0.186434,...,0.015479,0.000000,0.009901,0.000605,0.0,0.000000,0.000000,0.002465,0.000000,0.139220
LAMI.RD006.D0.C1,0.263692,0.172598,0.002682,0.003746,0.003519,0.137232,0.070689,0.191501,0.034915,0.081719,...,0.007302,0.000962,0.003203,0.004307,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD004.D0.C2,0.229692,0.084381,0.000304,0.000334,0.005276,0.039243,0.036240,0.364684,0.020890,0.111170,...,0.007987,0.000000,0.049028,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.006487
LAMI.RD014.D28.C1,0.068832,0.033293,0.000356,0.000493,0.002850,0.000000,0.018744,0.195317,0.009140,0.628209,...,0.005548,0.000000,0.004376,0.003408,0.0,0.000000,0.000000,0.005803,0.000000,0.007684
LAMI.RD014.D0.C1,0.100260,0.043915,0.000000,0.000305,0.005105,0.000000,0.024642,0.344354,0.008159,0.420984,...,0.007780,0.000000,0.005558,0.005134,0.0,0.000000,0.000000,0.020329,0.000000,0.000000
LAMI.RD001.D0.C1,0.265648,0.180123,0.002630,0.003544,0.002515,0.000000,0.086299,0.172743,0.050465,0.130990,...,0.005514,0.001103,0.054395,0.001492,0.0,0.000000,0.000000,0.000000,0.000000,0.011177
LAMI.RD014.D14.C2,0.141472,0.091256,0.002022,0.000369,0.002820,0.000000,0.036315,0.145703,0.022171,0.476106,...,0.005483,0.000555,0.003259,0.003412,0.0,0.000000,0.000000,0.016321,0.000000,0.019050
LAMI.RD001.D14.C2,0.150908,0.233283,0.000857,0.000000,0.001403,0.000000,0.092716,0.176654,0.052844,0.231220,...,0.014791,0.000686,0.019398,0.003245,0.0,0.000000,0.000000,0.000000,0.000000,0.002305

In [1103]:
# Save as biom for mmvec
metaB_V1V3_tbl_transposed = metaB_V1V3_tbl_relative.T
output_path = f'../Data/multi-omics/metabolomics-tbl_16S_V1V3-matched_relative_{skin_group}.biom'
save_as_biom(metaB_V1V3_tbl_relative, output_path)

In [1104]:
# Subset V1V3_tbl rows where sample is in metaB_tbl
V1V3_tbl_matched = V1V3_tbl[V1V3_tbl.index.isin(metaB_V1V3_tbl_relative.index)]

top_V1V3_features = [' g__Cutibacterium', ' g__Staphylococcus',
                     ' g__Streptococcus',' g__Lawsonella',
                     ' g__Micrococcus', ' g__Lactobacillus', 
                     ' g__Rothia', ' g__Kocuria', ' g__Haemophilus', ' g__Corynebacterium', ' g__Veillonella']

# top_V1V3_features = ['g__Cutibacterium|ASV1', 'g__Staphylococcus|ASV1',
#                      'g__Streptococcus|ASV1','g__Lawsonella',
#                      ' g__Micrococcus|ASV1', 'g__Lactobacillus|ASV1', 
#                      'g__Rothia|ASV1', 'g__Kocuria|ASV1', 'g__Haemophilus|ASV1', 'g__Corynebacterium|ASV1']

# Find the intersection of desired columns and actual DataFrame columns
available_columns = V1V3_tbl_matched.columns.intersection(top_V1V3_features)
V1V3_tbl_matched = V1V3_tbl_matched[available_columns]

V1V3_tbl_matched

,g__Cutibacterium,g__Staphylococcus,g__Streptococcus,g__Corynebacterium,g__Lawsonella,g__Veillonella,g__Micrococcus,g__Lactobacillus,g__Rothia,g__Haemophilus,g__Kocuria
LAMI.RD001.D0.C1,2362.0,94.0,292.0,175.0,91.0,33.0,37.0,1.0,50.0,87.0,0.0
LAMI.RD001.D0.C2,1808.0,158.0,374.0,352.0,120.0,36.0,52.0,165.0,43.0,74.0,9.0
LAMI.RD001.D14.C1,2234.0,83.0,240.0,492.0,253.0,19.0,30.0,60.0,12.0,8.0,0.0
LAMI.RD001.D14.C2,1761.0,137.0,446.0,456.0,151.0,69.0,16.0,26.0,31.0,58.0,6.0
LAMI.RD001.D28.C1,2367.0,118.0,293.0,365.0,217.0,34.0,22.0,17.0,14.0,10.0,5.0
LAMI.RD002.D0.C2,2900.0,373.0,159.0,39.0,13.0,2.0,61.0,1.0,27.0,11.0,54.0
LAMI.RD003.D14.C1,3296.0,95.0,14.0,138.0,14.0,0.0,0.0,1.0,5.0,0.0,0.0
LAMI.RD002.D14.C1,3440.0,105.0,43.0,49.0,41.0,0.0,7.0,2.0,4.0,1.0,0.0
LAMI.RD003.D28.C1,2367.0,103.0,543.0,31.0,36.0,0.0,0.0,0.0,16.0,21.0,0.0
LAMI.RD001.D28.C2,2288.0,204.0,169.0,399.0,420.0,25.0,20.0,11.0,20.0,11.0,9.0
LAMI.RD007.D0.C1,3707.0,23.0,16.0,0.0,7.0,2.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD002.D14.C2,3092.0,96.0,57.0,34.0,33.0,31.0,10.0,0.0,246.0,1.0,17.0
LAMI.RD006.D0.C1,3163.0,98.0,67.0,214.0,45.0,28.0,15.0,13.0,0.0,0.0,0.0
LAMI.RD011.D28.C1,3533.0,51.0,25.0,22.0,54.0,4.0,0.0,0.0,2.0,0.0,0.0
LAMI.RD007.D14.C1,3625.0,68.0,7.0,18.0,18.0,1.0,4.0,1.0,0.0,1.0,0.0
LAMI.RD002.D0.C1,3428.0,156.0,32.0,7.0,25.0,1.0,13.0,0.0,0.0,7.0,7.0
LAMI.RD006.D0.C2,3426.0,92.0,22.0,121.0,37.0,9.0,2.0,7.0,0.0,1.0,0.0
LAMI.RD007.D14.C2,3559.0,69.0,24.0,25.0,60.0,6.0,2.0,0.0,0.0,2.0,0.0
LAMI.RD002.D28.C2,3133.0,135.0,19.0,74.0,87.0,5.0,7.0,2.0,0.0,0.0,6.0
LAMI.RD004.D0.C1,2674.0,102.0,310.0,454.0,22.0,39.0,21.0,11.0,29.0,3.0,0.0
LAMI.RD006.D14.C2,3388.0,68.0,24.0,149.0,62.0,5.0,6.0,2.0,3.0,2.0,3.0
LAMI.RD018.D28.C1,3738.0,6.0,4.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD017.D0.C2,3724.0,18.0,2.0,4.0,11.0,1.0,7.0,0.0,0.0,0.0,0.0
LAMI.RD014.D0.C1,709.0,41.0,1435.0,57.0,112.0,216.0,405.0,0.0,64.0,2.0,6.0
LAMI.RD004.D0.C2,3037.0,287.0,79.0,221.0,31.0,16.0,0.0,6.0,8.0,4.0,0.0
LAMI.RD007.D28.C1,3680.0,63.0,5.0,8.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D14.C1,2681.0,51.0,309.0,296.0,114.0,8.0,15.0,45.0,15.0,2.0,7.0
LAMI.RD003.D0.C1,1981.0,58.0,384.0,49.0,15.0,46.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D28.C1,3154.0,77.0,108.0,81.0,40.0,18.0,45.0,27.0,0.0,0.0,0.0
LAMI.RD007.D28.C2,3671.0,27.0,24.0,15.0,18.0,2.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D28.C2,3745.0,8.0,7.0,3.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0
LAMI.RD014.D14.C2,3137.0,38.0,98.0,27.0,192.0,14.0,41.0,0.0,0.0,0.0,0.0
LAMI.RD004.D28.C2,1692.0,80.0,788.0,544.0,32.0,44.0,133.0,25.0,34.0,0.0,27.0
LAMI.RD014.D28.C1,1831.0,45.0,509.0,25.0,114.0,115.0,116.0,55.0,88.0,0.0,0.0
LAMI.RD017.D28.C2,3759.0,3.0,0.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0
LAMI.RD014.D28.C2,2156.0,130.0,259.0,67.0,316.0,63.0,251.0,8.0,51.0,5.0,12.0
LAMI.RD018.D0.C1,3710.0,1.0,0.0,7.0,0.0,0.0,9.0,2.0,0.0,0.0,32.0
LAMI.RD011.D0.C2,3344.0,274.0,28.0,23.0,45.0,2.0,8.0,0.0,2.0,1.0,8.0
LAMI.RD018.D0.C2,3636.0,2.0,35.0,14.0,0.0,6.0,3.0,0.0,1.0,1.0,23.0
LAMI.RD011.D14.C2,3488.0,30.0,1.0,7.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D14.C1,3675.0,7.0,20.0,6.0,0.0,3.0,0.0,0.0,5.0,0.0,1.0

In [1105]:
# Convert to relative abundance (row-wise normalization)
V1V3_tbl_matched_relative = V1V3_tbl_matched.div(V1V3_tbl_matched.sum(axis=1), axis=0)
V1V3_tbl_matched_relative

,g__Cutibacterium,g__Staphylococcus,g__Streptococcus,g__Corynebacterium,g__Lawsonella,g__Veillonella,g__Micrococcus,g__Lactobacillus,g__Rothia,g__Haemophilus,g__Kocuria
LAMI.RD001.D0.C1,0.733085,0.029174,0.090627,0.054314,0.028243,0.010242,0.011484,0.000310,0.015518,0.027002,0.000000
LAMI.RD001.D0.C2,0.566594,0.049514,0.117205,0.110310,0.037606,0.011282,0.016296,0.051708,0.013475,0.023190,0.002820
LAMI.RD001.D14.C1,0.651122,0.024191,0.069950,0.143398,0.073739,0.005538,0.008744,0.017488,0.003498,0.002332,0.000000
LAMI.RD001.D14.C2,0.557808,0.043396,0.141273,0.144441,0.047830,0.021856,0.005068,0.008236,0.009819,0.018372,0.001901
LAMI.RD001.D28.C1,0.683709,0.034084,0.084633,0.105430,0.062681,0.009821,0.006355,0.004910,0.004044,0.002889,0.001444
LAMI.RD002.D0.C2,0.796703,0.102473,0.043681,0.010714,0.003571,0.000549,0.016758,0.000275,0.007418,0.003022,0.014835
LAMI.RD003.D14.C1,0.925063,0.026663,0.003929,0.038731,0.003929,0.000000,0.000000,0.000281,0.001403,0.000000,0.000000
LAMI.RD002.D14.C1,0.931744,0.028440,0.011647,0.013272,0.011105,0.000000,0.001896,0.000542,0.001083,0.000271,0.000000
LAMI.RD003.D28.C1,0.759384,0.033045,0.174206,0.009945,0.011550,0.000000,0.000000,0.000000,0.005133,0.006737,0.000000
LAMI.RD001.D28.C2,0.639821,0.057047,0.047260,0.111577,0.117450,0.006991,0.005593,0.003076,0.005593,0.003076,0.002517
LAMI.RD007.D0.C1,0.987217,0.006125,0.004261,0.000000,0.001864,0.000533,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD002.D14.C2,0.854852,0.026541,0.015759,0.009400,0.009124,0.008571,0.002765,0.000000,0.068012,0.000276,0.004700
LAMI.RD006.D0.C1,0.868240,0.026901,0.018391,0.058743,0.012352,0.007686,0.004117,0.003568,0.000000,0.000000,0.000000
LAMI.RD011.D28.C1,0.957193,0.013817,0.006773,0.005960,0.014630,0.001084,0.000000,0.000000,0.000542,0.000000,0.000000
LAMI.RD007.D14.C1,0.968474,0.018167,0.001870,0.004809,0.004809,0.000267,0.001069,0.000267,0.000000,0.000267,0.000000
LAMI.RD002.D0.C1,0.932535,0.042437,0.008705,0.001904,0.006801,0.000272,0.003536,0.000000,0.000000,0.001904,0.001904
LAMI.RD006.D0.C2,0.921711,0.024751,0.005919,0.032553,0.009954,0.002421,0.000538,0.001883,0.000000,0.000269,0.000000
LAMI.RD007.D14.C2,0.949827,0.018415,0.006405,0.006672,0.016013,0.001601,0.000534,0.000000,0.000000,0.000534,0.000000
LAMI.RD002.D28.C2,0.903403,0.038927,0.005479,0.021338,0.025087,0.001442,0.002018,0.000577,0.000000,0.000000,0.001730
LAMI.RD004.D0.C1,0.729604,0.027831,0.084584,0.123874,0.006003,0.010641,0.005730,0.003001,0.007913,0.000819,0.000000
LAMI.RD006.D14.C2,0.912716,0.018319,0.006466,0.040140,0.016703,0.001347,0.001616,0.000539,0.000808,0.000539,0.000808
LAMI.RD018.D28.C1,0.996003,0.001599,0.001066,0.000799,0.000533,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD017.D0.C2,0.988585,0.004778,0.000531,0.001062,0.002920,0.000265,0.001858,0.000000,0.000000,0.000000,0.000000
LAMI.RD014.D0.C1,0.232688,0.013456,0.470955,0.018707,0.036757,0.070889,0.132918,0.000000,0.021004,0.000656,0.001969
LAMI.RD004.D0.C2,0.823258,0.077799,0.021415,0.059908,0.008403,0.004337,0.000000,0.001626,0.002169,0.001084,0.000000
LAMI.RD007.D28.C1,0.978463,0.016751,0.001329,0.002127,0.001329,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD006.D14.C1,0.756703,0.014395,0.087214,0.083545,0.032176,0.002258,0.004234,0.012701,0.004234,0.000564,0.001976
LAMI.RD003.D0.C1,0.782077,0.022898,0.151599,0.019345,0.005922,0.018160,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD006.D28.C1,0.888451,0.021690,0.030423,0.022817,0.011268,0.005070,0.012676,0.007606,0.000000,0.000000,0.000000
LAMI.RD007.D28.C2,0.977109,0.007187,0.006388,0.003993,0.004791,0.000532,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD018.D28.C2,0.994160,0.002124,0.001858,0.000796,0.000000,0.000531,0.000000,0.000000,0.000531,0.000000,0.000000
LAMI.RD014.D14.C2,0.884409,0.010713,0.027629,0.007612,0.054130,0.003947,0.011559,0.000000,0.000000,0.000000,0.000000
LAMI.RD004.D28.C2,0.497793,0.023536,0.231833,0.160047,0.009415,0.012945,0.039129,0.007355,0.010003,0.000000,0.007944
LAMI.RD014.D28.C1,0.631815,0.015528,0.175638,0.008627,0.039337,0.039683,0.040028,0.018979,0.030366,0.000000,0.000000
LAMI.RD017.D28.C2,0.997347,0.000796,0.000000,0.000000,0.001061,0.000000,0.000796,0.000000,0.000000,0.000000,0.000000
LAMI.RD014.D28.C2,0.649789,0.039180,0.078059,0.020193,0.095238,0.018987,0.075648,0.002411,0.015371,0.001507,0.003617
LAMI.RD018.D0.C1,0.986440,0.000266,0.000000,0.001861,0.000000,0.000000,0.002393,0.000532,0.000000,0.000000,0.008508
LAMI.RD011.D0.C2,0.895315,0.073360,0.007497,0.006158,0.012048,0.000535,0.002142,0.000000,0.000535,0.000268,0.002142
LAMI.RD018.D0.C2,0.977157,0.000537,0.009406,0.003762,0.000000,0.001612,0.000806,0.000000,0.000269,0.000269,0.006181
LAMI.RD011.D14.C2,0.986984,0.008489,0.000283,0.001981,0.001981,0.000283,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD018.D14.C1,0.988701,0.001883,0.005381,0.001614,0.000000,0.000807,0.000000,0.000000,0.001345,0.000000,0.000269

In [1106]:
# Save metadata for V1V3
metadata_V1V3 = metadata[metadata['SampleID'].isin(V1V3_tbl_matched_relative.index)]
metadata_V1V3 = metadata_V1V3[['SampleID', 'group']]

# Rename the first column to 'sample id'
metadata_V1V3.rename(columns={metadata_V1V3.columns[0]: 'sample id'}, inplace=True)

# Remove the name of the second column (set it to an empty string)
metadata_V1V3.columns = ['sample id'] + ['' if i == 1 else col for i, col in enumerate(metadata_V1V3.columns[1:])]

metadata_V1V3.to_csv('../Data/multi-omics/16S_V1V3_metaB-matched.csv', index=0)
metadata_V1V3

             sample id    group
9    LAMI.RD002.D14.C1  Healthy
14   LAMI.RD003.D14.C1  Healthy
22    LAMI.RD017.D0.C2  Healthy
27   LAMI.RD007.D14.C1  Healthy
28   LAMI.RD017.D28.C2  Healthy
30   LAMI.RD002.D28.C2  Healthy
33    LAMI.RD004.D0.C1  Healthy
36   LAMI.RD003.D28.C1  Healthy
38   LAMI.RD001.D14.C1  Healthy
45   LAMI.RD001.D28.C1  Healthy
54   LAMI.RD002.D14.C2  Healthy
56   LAMI.RD006.D28.C1  Healthy
58   LAMI.RD006.D14.C1  Healthy
59   LAMI.RD011.D28.C1  Healthy
64   LAMI.RD007.D14.C2  Healthy
65   LAMI.RD014.D28.C2  Healthy
66    LAMI.RD018.D0.C2  Healthy
84    LAMI.RD003.D0.C1  Healthy
88   LAMI.RD011.D14.C2  Healthy
95    LAMI.RD002.D0.C2  Healthy
108   LAMI.RD007.D0.C1  Healthy
113  LAMI.RD018.D28.C2  Healthy
114  LAMI.RD007.D28.C1  Healthy
124  LAMI.RD007.D28.C2  Healthy
127   LAMI.RD001.D0.C2  Healthy
136   LAMI.RD006.D0.C2  Healthy
151   LAMI.RD018.D0.C1  Healthy
154   LAMI.RD002.D0.C1  Healthy
167  LAMI.RD018.D28.C1  Healthy
189  LAMI.RD018.D14.C1  Healthy
204  LAMI.RD006.D14.C2  Healthy
205  LAMI.RD001.D28.C2  Healthy
209  LAMI.RD004.D28.C2  Healthy
216   LAMI.RD011.D0.C2  Healthy
219   LAMI.RD006.D0.C1  Healthy
239   LAMI.RD004.D0.C2  Healthy
240  LAMI.RD014.D28.C1  Healthy
244   LAMI.RD014.D0.C1  Healthy
262   LAMI.RD001.D0.C1  Healthy
263  LAMI.RD014.D14.C2  Healthy
265  LAMI.RD001.D14.C2  Healthy

In [1107]:
# Save as biom for mmvec
V1V3_tbl_matched_transposed = V1V3_tbl_matched_relative.T
output_path = f'../Data/multi-omics/16S_V1V3-tbl_metaB-matched_relative_{skin_group}.biom'
save_as_biom(V1V3_tbl_matched_transposed, output_path)

In [1108]:
# Create column_names_df with 'feature id' as the column header
column_names_df = pd.DataFrame({"feature id": metaB_V1V3_tbl.columns})  # Ensure feature id is a string

column_names_df

                                           feature id
0   Pyroglutamic acid (mz: 130.0497016, RT: 0.6479...
1      (Iso)leucine (mz: 132.1017009, RT: 0.71511286)
2      Urocanic acid (mz: 139.0410336, RT: 0.6406374)
3      Urocanic acid (mz: 139.0587028, RT: 0.6315576)
4        Paracetamol (mz: 152.0704373, RT: 1.6221956)
5            Nicotine (mz: 163.1224157, RT: 0.634317)
6       Phenylalanine (mz: 166.086109, RT: 0.9777797)
7           Tyrosine (mz: 182.0809391, RT: 0.6720225)
8         Tryptophan (mz: 205.0969182, RT: 2.0760007)
9       DL-Panthenol (mz: 206.1384472, RT: 1.1194918)
10    Cyclo(his-pro) (mz: 235.1186308, RT: 0.6402779)
11          Uridine (mz: 245.0765944, RT: 0.65536463)
12    xylometazoline (mz: 245.2008949, RT: 4.3418465)
13  Phenylbenzimidazole sulfonic acid (mz: 275.048...
14       (Iso)leucine (mz: 276.143683, RT: 0.6789317)
15  Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)
16  C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7...
17  N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1...
18          Gln-C14:0 (mz: 357.2754847, RT: 5.845114)
19         Sinensetin (mz: 373.127569, RT: 5.0247345)
20           Nobiletin (mz: 403.138254, RT: 5.258404)
21  Sorbitane Monooleate (mz: 428.3728208, RT: 6.1...
22  3-O-methylated flavonoids (mz: 433.1489336, RT...
23   NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)

In [1109]:
# Save to a CSV file
output_path = "../Data/multi-omics/metabolite_info.csv"
column_names_df = column_names_df.to_csv(output_path, index=0)

In [1110]:
# Subset metaB rows where sample is in V4_tbl
metaB_V4_tbl = metaB_tbl[metaB_tbl.index.isin(V4_tbl.index)]
# metaB_V4_tbl = metaB_V4_tbl.drop('group', axis=1)
metaB_V4_tbl.index.name = None
metaB_V4_tbl

,"Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Paracetamol (mz: 152.0704373, RT: 1.6221956)","Nicotine (mz: 163.1224157, RT: 0.634317)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","DL-Panthenol (mz: 206.1384472, RT: 1.1194918)",...,"(Iso)leucine (mz: 276.143683, RT: 0.6789317)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1323557)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","Nobiletin (mz: 403.138254, RT: 5.258404)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)"
LAMI.RD001.D0.C1,2987383.80,2025607.40,29574.6480,39859.7580,28277.594,0.00,970487.500,1942604.500,567510.060,1473068.10,...,62007.1100,12406.8260,611709.700,16778.8380,0.0000,0.000,0.000,0.00,0.000,125692.330
LAMI.RD306.D9.C2,2051791.50,2260333.20,34466.4840,0.0000,253083.810,178911.47,1071868.200,3572847.500,672054.400,308019.97,...,153381.2700,20433.4900,437938.200,12865.3900,0.0000,0.000,0.000,0.00,0.000,10553.927
LAMI.RD304.D11.C1,1818308.60,1434033.20,47379.2730,36750.4000,15391.807,0.00,595568.940,1605551.000,328151.120,299140.06,...,58588.9260,9403.6520,78491.530,0.0000,5375.8525,11225.194,23546.951,99470.69,29824.627,12473.092
LAMI.RD304.D11.C2,1126503.20,706197.75,3460.0974,0.0000,15015.189,0.00,303845.300,865753.500,152392.720,191713.67,...,20153.3320,2286.2397,261996.800,15780.3090,2691.0256,16378.752,34863.656,157503.92,44084.586,40673.110
LAMI.RD304.D0.C1,827466.30,778566.10,4547.2640,3345.8184,45187.030,0.00,293386.340,1321474.400,137201.390,705570.80,...,45193.9400,0.0000,427202.060,3228.1143,3431.0034,0.000,0.000,0.00,0.000,49464.902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LAMI.RD318.D9.C3,1173415.00,1250164.60,8613.8590,9787.1210,14712.559,0.00,579058.800,1380958.500,498893.780,236111.75,...,24563.9240,5144.6616,122958.260,56654.0430,0.0000,0.000,0.000,0.00,0.000,0.000
LAMI.RD308.D9.C3,550094.94,687527.06,3163.9185,3076.9688,17934.553,0.00,281896.700,742416.600,262886.470,303509.40,...,24480.3900,0.0000,65659.700,21826.1170,0.0000,0.000,0.000,0.00,0.000,220846.160
LAMI.RD319.D2.C2,602147.10,538412.94,4006.6484,0.0000,10556.326,0.00,255542.720,1194061.900,121803.890,5406879.00,...,35224.5800,0.0000,73231.560,19741.2460,0.0000,0.000,0.000,0.00,0.000,25695.014
LAMI.RD319.D2.C3,171846.72,106901.95,0.0000,1407.5230,25369.129,0.00,59064.336,833009.000,23485.404,2838344.20,...,25342.2100,0.0000,55986.290,0.0000,0.0000,0.000,0.000,0.00,0.000,11039.730
LAMI.RD318.D21.C2,400723.72,365100.34,4839.8540,0.0000,20615.168,0.00,185104.470,20027.605,116420.730,364993.20,...,6948.2324,0.0000,53308.617,18413.5040,0.0000,0.000,0.000,0.00,0.000,73266.420

In [1111]:
# Drop the column from the DataFrame as it wasn't significant after univariate testing
# metaB_V4_tbl = metaB_V4_tbl.drop(columns=['C19H22O4 Linear diarylheptanoids'])

In [1112]:
# Convert to relative abundance (row-wise normalization)
metaB_V4_tbl_relative = metaB_V4_tbl.div(metaB_V4_tbl.sum(axis=1), axis=0)
metaB_V4_tbl_relative

,"Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Paracetamol (mz: 152.0704373, RT: 1.6221956)","Nicotine (mz: 163.1224157, RT: 0.634317)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","DL-Panthenol (mz: 206.1384472, RT: 1.1194918)",...,"(Iso)leucine (mz: 276.143683, RT: 0.6789317)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1323557)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","Nobiletin (mz: 403.138254, RT: 5.258404)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)"
LAMI.RD001.D0.C1,0.265648,0.180123,0.002630,0.003544,0.002515,0.000000,0.086299,0.172743,0.050465,0.130990,...,0.005514,0.001103,0.054395,0.001492,0.000000,0.000000,0.000000,0.000000,0.000000,0.011177
LAMI.RD306.D9.C2,0.177092,0.195092,0.002975,0.000000,0.021844,0.015442,0.092514,0.308376,0.058006,0.026585,...,0.013238,0.001764,0.037799,0.001110,0.000000,0.000000,0.000000,0.000000,0.000000,0.000911
LAMI.RD304.D11.C1,0.269227,0.212329,0.007015,0.005441,0.002279,0.000000,0.088183,0.237725,0.048588,0.044292,...,0.008675,0.001392,0.011622,0.000000,0.000796,0.001662,0.003486,0.014728,0.004416,0.001847
LAMI.RD304.D11.C2,0.274761,0.172246,0.000844,0.000000,0.003662,0.000000,0.074110,0.211162,0.037169,0.046760,...,0.004916,0.000558,0.063903,0.003849,0.000656,0.003995,0.008503,0.038416,0.010752,0.009920
LAMI.RD304.D0.C1,0.172611,0.162410,0.000949,0.000698,0.009426,0.000000,0.061201,0.275662,0.028620,0.147184,...,0.009428,0.000000,0.089115,0.000673,0.000716,0.000000,0.000000,0.000000,0.000000,0.010318
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LAMI.RD318.D9.C3,0.210388,0.224149,0.001544,0.001755,0.002638,0.000000,0.103823,0.247600,0.089449,0.042334,...,0.004404,0.000922,0.022046,0.010158,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LAMI.RD308.D9.C3,0.139416,0.174247,0.000802,0.000780,0.004545,0.000000,0.071444,0.188158,0.066626,0.076921,...,0.006204,0.000000,0.016641,0.005532,0.000000,0.000000,0.000000,0.000000,0.000000,0.055971
LAMI.RD319.D2.C2,0.071895,0.064285,0.000478,0.000000,0.001260,0.000000,0.030511,0.142568,0.014543,0.645566,...,0.004206,0.000000,0.008744,0.002357,0.000000,0.000000,0.000000,0.000000,0.000000,0.003068
LAMI.RD319.D2.C3,0.040939,0.025467,0.000000,0.000335,0.006044,0.000000,0.014071,0.198447,0.005595,0.676175,...,0.006037,0.000000,0.013338,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002630
LAMI.RD318.D21.C2,0.238046,0.216884,0.002875,0.000000,0.012246,0.000000,0.109960,0.011897,0.069159,0.216821,...,0.004128,0.000000,0.031667,0.010938,0.000000,0.000000,0.000000,0.000000,0.000000,0.043523

In [1113]:
# Filter metadata for the correct group
filtered_metadata = metadata[metadata['group'] == skin_group]

# Normalize SampleID and index formatting
metaB_V4_tbl_relative.index = metaB_V4_tbl_relative.index.str.strip().str.upper()
filtered_metadata['SampleID'] = filtered_metadata['SampleID'].str.strip().str.upper()

# Filter metadata to only include matching SampleIDs
filtered_metadata = filtered_metadata[filtered_metadata['SampleID'].isin(metaB_V4_tbl_relative.index)]

# Subset the DataFrame
metaB_V4_tbl_relative = metaB_V4_tbl_relative.loc[filtered_metadata['SampleID']]

metaB_V4_tbl_relative

/var/folders/22/yck9vwx53w1c38tvj_c0_tz00000gn/T/ipykernel_3481/4148729606.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_metadata['SampleID'] = filtered_metadata['SampleID'].str.strip().str.upper()

,"Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Paracetamol (mz: 152.0704373, RT: 1.6221956)","Nicotine (mz: 163.1224157, RT: 0.634317)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","DL-Panthenol (mz: 206.1384472, RT: 1.1194918)",...,"(Iso)leucine (mz: 276.143683, RT: 0.6789317)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1323557)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","Nobiletin (mz: 403.138254, RT: 5.258404)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)"
LAMI.RD017.D0.C1,0.267509,0.198181,0.000000,0.000799,0.002173,0.001165,0.105062,0.223399,0.069073,0.044435,...,0.007956,0.000000,0.031120,0.003507,0.000445,0.0,0.000000,0.004438,0.0,0.000000
LAMI.RD017.D0.C2,0.225856,0.195690,0.000000,0.000997,0.001983,0.002688,0.096634,0.287196,0.056365,0.033499,...,0.008864,0.000000,0.037747,0.003979,0.000000,0.0,0.000000,0.003933,0.0,0.000581
LAMI.RD007.D14.C1,0.206929,0.171066,0.001356,0.000000,0.005920,0.010829,0.076215,0.302280,0.027798,0.095579,...,0.008078,0.000993,0.054766,0.003050,0.000000,0.0,0.000000,0.000000,0.0,0.017369
LAMI.RD017.D28.C2,0.241377,0.257380,0.000284,0.000256,0.000982,0.010516,0.127992,0.205061,0.077467,0.012105,...,0.005975,0.002195,0.024483,0.003850,0.000000,0.0,0.000000,0.001510,0.0,0.000335
LAMI.RD004.D0.C1,0.177376,0.094539,0.000904,0.001157,0.003262,0.019609,0.038629,0.277297,0.028480,0.262060,...,0.008955,0.000168,0.058771,0.000000,0.000000,0.0,0.000000,0.004322,0.0,0.000000
LAMI.RD001.D14.C1,0.230963,0.232861,0.003391,0.002454,0.001484,0.000888,0.105728,0.195136,0.049886,0.035618,...,0.006185,0.003094,0.080559,0.000359,0.000000,0.0,0.000000,0.000000,0.0,0.000000
LAMI.RD001.D28.C1,0.295443,0.196816,0.002237,0.003003,0.003460,0.000270,0.104208,0.208874,0.075193,0.021648,...,0.007380,0.005108,0.015558,0.001258,0.000000,0.0,0.000000,0.002090,0.0,0.002443
LAMI.RD017.D28.C1,0.220370,0.251676,0.002644,0.000304,0.001835,0.011191,0.117802,0.229543,0.074486,0.022402,...,0.010360,0.001639,0.026570,0.003333,0.000000,0.0,0.000000,0.001841,0.0,0.000000
LAMI.RD017.D14.C2,0.266732,0.226188,0.001128,0.000513,0.001460,0.002557,0.097817,0.189710,0.055908,0.097200,...,0.003415,0.001375,0.026563,0.001489,0.000274,0.0,0.000000,0.000730,0.0,0.002643
LAMI.RD006.D14.C1,0.087079,0.037841,0.000000,0.000344,0.000427,0.008884,0.014522,0.052685,0.008457,0.779160,...,0.001562,0.000000,0.000313,0.001936,0.000000,0.0,0.000000,0.000000,0.0,0.000541
LAMI.RD007.D14.C2,0.206547,0.168960,0.000429,0.000334,0.005719,0.014434,0.069950,0.353268,0.030642,0.098004,...,0.011326,0.000818,0.014396,0.000695,0.000000,0.0,0.000000,0.000000,0.0,0.006568
LAMI.RD018.D0.C2,0.161313,0.159250,0.001568,0.007939,0.007427,0.021588,0.067975,0.296047,0.043221,0.100254,...,0.018767,0.000000,0.062964,0.001525,0.000000,0.0,0.002178,0.000000,0.0,0.021104
LAMI.RD011.D14.C2,0.098061,0.082586,0.000550,0.000000,0.001354,0.000000,0.032164,0.120290,0.017096,0.622115,...,0.005693,0.000195,0.002874,0.000751,0.000000,0.0,0.000000,0.000000,0.0,0.001931
LAMI.RD007.D28.C1,0.182298,0.152776,0.000000,0.000000,0.009969,0.008638,0.064433,0.226915,0.023081,0.077988,...,0.006204,0.000000,0.209593,0.002076,0.000000,0.0,0.000000,0.000000,0.0,0.020231
LAMI.RD007.D28.C2,0.231895,0.184723,0.005339,0.000414,0.003776,0.015688,0.086177,0.247069,0.046920,0.059466,...,0.006896,0.000000,0.070455,0.002839,0.000000,0.0,0.000000,0.008954,0.0,0.000000
LAMI.RD001.D0.C2,0.225045,0.160554,0.001287,0.001263,0.001349,0.000348,0.071860,0.168027,0.038263,0.236712,...,0.005661,0.001188,0.049936,0.000379,0.000000,0.0,0.000000,0.000000,0.0,0.004045
LAMI.RD018.D0.C1,0.253247,0.203595,0.001172,0.001450,0.006066,0.032272,0.076093,0.246301,0.038094,0.045951,...,0.007959,0.001962,0.052010,0.003533,0.000000,0.0,0.003149,0.000000,0.0,0.000000
LAMI.RD006.D14.C2,0.080630,0.052253,0.000496,0.001050,0.000623,0.004973,0.022194,0.063834,0.013500,0.745155,...,0.002312,0.000173,0.000633,0.002730,0.000000,0.0,0.000000,0.000458,0.0,0.000268
LAMI.RD001.D28.C2,0.317870,0.198551,0.006032,0.003829,0.005223,0.000628,0.089775,0.205688,0.049229,0.023498,...,0.006721,0.003011,0.041083,0.001776,0.000000,0.0,0.000000,0.000000,0.0,0.001790
LAMI.RD004.D28.C2,0.246397,0.109640,0.000000,0.000000,0.004873,0.047656,0.049982,0.281812,0.034234,0.098307,...,0.001965,0.000000,0.045287,0.000000,0.000000,0.0,0.000000,0.010320,0.0,0.000000
LAMI.RD011.D0.C2,0.106911,0.102710,0.000000,0.000000,0.006828,0.000693,0.046251,0.337303,0.019839,0.186434,...,0.015479,0.000000,0.009901,0.000605,0.000000,0.0,0.000000,0.002465,0.0,0.139220
LAMI.RD004.D0.C2,0.229692,0.084381,0.000304,0.000334,0.005276,0.039243,0.036240,0.364684,0.020890,0.111170,...,0.007987,0.000000,0.049028,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.006487
LAMI.RD011.D14.C1,0.071854,0.046040,0.000000,0.000000,0.002820,0.000000,0.017881,0.120499,0.004844,0.711293,...,0.002572,0.000000,0.005441,0.002235,0.000000,0.0,0.000000,0.000000,0.0,0.006388
LAMI.RD001.D0.C1,0.265648,0.180123,0.002630,0.003544,0.002515,0.000000,0.086299,0.172743,0.050465,0.130990,...,0.005514,0.001103,0.054395,0.001492,0.000000,0.0,0.000000,0.000000,0.0,0.011177
LAMI.RD001.D14.C2,0.150908,0.233283,0.000857,0.000000,0.001403,0.000000,0.092716,0.176654,0.052844,0.231220,...,0.014791,0.000686,0.019398,0.003245,0.000000,0.0,0.000000,0.000000,0.0,0.002305

In [1114]:
# Subset V4_tbl rows where sample is in metaB_tbl
V4_tbl_matched = V4_tbl[V4_tbl.index.isin(metaB_V4_tbl_relative.index)]

# top_V4_features = [' g__Staphylococcus', ' g__Lawsonella',
#                     ' g__Streptococcus', ' g__Acinetobacter', ' g__Cutibacterium', 'g__Enhydrobacter',
#                      ' g__Micrococcus', ' g__Lactobacillus', ' g__Rothia', ' g__Kocuria', ' g__Haemophilus', ' g__Corynebacterium']


top_V4_features = [' g__Staphylococcus', ' g__Lawsonella', ' g__Streptococcus', ' g__Cutibacterium',
                     ' g__Micrococcus', ' g__Lactobacillus', ' g__Rothia', ' g__Kocuria', ' g__Haemophilus', ' g__Corynebacterium', ' g__Veillonella']

# Find the intersection of desired columns and actual DataFrame columns
available_columns = V4_tbl_matched.columns.intersection(top_V4_features)
V4_tbl_matched = V4_tbl_matched[available_columns]

V4_tbl_matched

,g__Staphylococcus,g__Lawsonella,g__Corynebacterium,g__Streptococcus,g__Haemophilus,g__Micrococcus,g__Lactobacillus,g__Veillonella,g__Cutibacterium,g__Kocuria,g__Rothia
LAMI.RD001.D0.C1,317.0,131.0,275.0,414.0,475.0,100.0,15.0,43.0,1.0,17.0,36.0
LAMI.RD001.D14.C1,454.0,456.0,915.0,247.0,168.0,93.0,117.0,41.0,0.0,5.0,15.0
LAMI.RD004.D0.C2,1652.0,95.0,848.0,164.0,28.0,81.0,97.0,59.0,1.0,18.0,49.0
LAMI.RD001.D0.C2,349.0,217.0,509.0,368.0,464.0,75.0,182.0,37.0,3.0,3.0,56.0
LAMI.RD011.D0.C2,2132.0,291.0,220.0,153.0,227.0,60.0,26.0,32.0,3.0,44.0,27.0
LAMI.RD001.D14.C2,444.0,206.0,546.0,457.0,456.0,54.0,23.0,83.0,0.0,5.0,47.0
LAMI.RD004.D28.C2,217.0,18.0,731.0,713.0,44.0,276.0,40.0,115.0,2.0,16.0,15.0
LAMI.RD017.D14.C2,1756.0,636.0,131.0,33.0,25.0,617.0,2.0,0.0,126.0,7.0,1.0
LAMI.RD011.D14.C1,2063.0,999.0,102.0,85.0,37.0,88.0,45.0,15.0,32.0,3.0,7.0
LAMI.RD004.D0.C1,603.0,48.0,875.0,270.0,14.0,83.0,21.0,21.0,6.0,5.0,30.0
LAMI.RD001.D28.C1,580.0,457.0,692.0,349.0,142.0,72.0,83.0,50.0,1.0,5.0,34.0
LAMI.RD017.D28.C1,1189.0,268.0,120.0,202.0,95.0,237.0,14.0,32.0,69.0,5.0,2.0
LAMI.RD011.D14.C2,567.0,112.0,59.0,15.0,2.0,0.0,6.0,8.0,12.0,6.0,1.0
LAMI.RD017.D0.C1,2876.0,168.0,119.0,88.0,23.0,181.0,0.0,19.0,65.0,2.0,0.0
LAMI.RD017.D28.C2,1543.0,516.0,195.0,73.0,16.0,599.0,8.0,5.0,110.0,22.0,0.0
LAMI.RD007.D14.C1,2026.0,349.0,279.0,176.0,77.0,36.0,6.0,73.0,22.0,0.0,31.0
LAMI.RD007.D14.C2,1498.0,447.0,354.0,144.0,139.0,61.0,0.0,59.0,39.0,0.0,0.0
LAMI.RD017.D0.C2,1963.0,309.0,292.0,94.0,94.0,515.0,0.0,23.0,87.0,0.0,0.0
LAMI.RD018.D0.C1,341.0,11.0,610.0,186.0,24.0,395.0,13.0,30.0,59.0,1023.0,16.0
LAMI.RD001.D28.C2,849.0,493.0,862.0,279.0,114.0,77.0,30.0,58.0,4.0,5.0,25.0
LAMI.RD018.D0.C2,381.0,43.0,481.0,547.0,85.0,165.0,0.0,107.0,75.0,167.0,66.0
LAMI.RD007.D28.C1,2634.0,136.0,192.0,181.0,93.0,15.0,25.0,12.0,33.0,1.0,0.0
LAMI.RD006.D14.C1,487.0,169.0,523.0,456.0,5.0,129.0,205.0,56.0,12.0,73.0,30.0
LAMI.RD007.D28.C2,1734.0,379.0,536.0,19.0,138.0,15.0,30.0,30.0,50.0,1.0,3.0
LAMI.RD006.D14.C2,706.0,354.0,768.0,107.0,13.0,150.0,130.0,37.0,12.0,30.0,0.0

In [1115]:
# Convert to relative abundance (row-wise normalization)
V4_tbl_matched_relative = V4_tbl_matched.div(V4_tbl_matched.sum(axis=1), axis=0)
V4_tbl_matched_relative

,g__Staphylococcus,g__Lawsonella,g__Corynebacterium,g__Streptococcus,g__Haemophilus,g__Micrococcus,g__Lactobacillus,g__Veillonella,g__Cutibacterium,g__Kocuria,g__Rothia
LAMI.RD001.D0.C1,0.173794,0.071820,0.150768,0.226974,0.260417,0.054825,0.008224,0.023575,0.000548,0.009320,0.019737
LAMI.RD001.D14.C1,0.180804,0.181601,0.364397,0.098367,0.066906,0.037037,0.046595,0.016328,0.000000,0.001991,0.005974
LAMI.RD004.D0.C2,0.534282,0.030724,0.274256,0.053040,0.009056,0.026197,0.031371,0.019082,0.000323,0.005821,0.015847
LAMI.RD001.D0.C2,0.154220,0.095890,0.224923,0.162616,0.205038,0.033142,0.080424,0.016350,0.001326,0.001326,0.024746
LAMI.RD011.D0.C2,0.663142,0.090513,0.068429,0.047589,0.070607,0.018663,0.008087,0.009953,0.000933,0.013686,0.008398
LAMI.RD001.D14.C2,0.191297,0.088755,0.235243,0.196898,0.196467,0.023266,0.009910,0.035760,0.000000,0.002154,0.020250
LAMI.RD004.D28.C2,0.099223,0.008230,0.334248,0.326017,0.020119,0.126200,0.018290,0.052583,0.000914,0.007316,0.006859
LAMI.RD017.D14.C2,0.526695,0.190762,0.039292,0.009898,0.007499,0.185063,0.000600,0.000000,0.037792,0.002100,0.000300
LAMI.RD011.D14.C1,0.593498,0.287399,0.029344,0.024453,0.010644,0.025316,0.012946,0.004315,0.009206,0.000863,0.002014
LAMI.RD004.D0.C1,0.305162,0.024291,0.442814,0.136640,0.007085,0.042004,0.010628,0.010628,0.003036,0.002530,0.015182
LAMI.RD001.D28.C1,0.235294,0.185396,0.280730,0.141582,0.057606,0.029209,0.033671,0.020284,0.000406,0.002028,0.013793
LAMI.RD017.D28.C1,0.532468,0.120018,0.053739,0.090461,0.042544,0.106135,0.006270,0.014330,0.030900,0.002239,0.000896
LAMI.RD011.D14.C2,0.719543,0.142132,0.074873,0.019036,0.002538,0.000000,0.007614,0.010152,0.015228,0.007614,0.001269
LAMI.RD017.D0.C1,0.812200,0.047444,0.033606,0.024852,0.006495,0.051116,0.000000,0.005366,0.018356,0.000565,0.000000
LAMI.RD017.D28.C2,0.499838,0.167153,0.063168,0.023648,0.005183,0.194040,0.002592,0.001620,0.035633,0.007127,0.000000
LAMI.RD007.D14.C1,0.658862,0.113496,0.090732,0.057236,0.025041,0.011707,0.001951,0.023740,0.007154,0.000000,0.010081
LAMI.RD007.D14.C2,0.546516,0.163079,0.129150,0.052536,0.050711,0.022255,0.000000,0.021525,0.014228,0.000000,0.000000
LAMI.RD017.D0.C2,0.581285,0.091501,0.086467,0.027835,0.027835,0.152502,0.000000,0.006811,0.025763,0.000000,0.000000
LAMI.RD018.D0.C1,0.125923,0.004062,0.225258,0.068685,0.008863,0.145864,0.004801,0.011078,0.021787,0.377770,0.005908
LAMI.RD001.D28.C2,0.303648,0.176323,0.308298,0.099785,0.040773,0.027539,0.010730,0.020744,0.001431,0.001788,0.008941
LAMI.RD018.D0.C2,0.179972,0.020312,0.227208,0.258385,0.040151,0.077940,0.000000,0.050543,0.035427,0.078885,0.031176
LAMI.RD007.D28.C1,0.792896,0.040939,0.057797,0.054485,0.027995,0.004515,0.007526,0.003612,0.009934,0.000301,0.000000
LAMI.RD006.D14.C1,0.227040,0.078788,0.243823,0.212587,0.002331,0.060140,0.095571,0.026107,0.005594,0.034033,0.013986
LAMI.RD007.D28.C2,0.590801,0.129131,0.182624,0.006474,0.047019,0.005111,0.010221,0.010221,0.017036,0.000341,0.001022
LAMI.RD006.D14.C2,0.306025,0.153446,0.332900,0.046381,0.005635,0.065020,0.056350,0.016038,0.005202,0.013004,0.000000

In [1116]:
# Save metadata for V4
metadata_V4 = metadata[metadata['SampleID'].isin(V4_tbl_matched.index)]
metadata_V4 = metadata_V4[['SampleID', 'group']]
# Rename the first column to 'sample id'
metadata_V4.rename(columns={metadata_V4.columns[0]: 'sample id'}, inplace=True)

# Remove the name of the second column (set it to an empty string)
metadata_V4.columns = ['sample id'] + ['' if i == 1 else col for i, col in enumerate(metadata_V4.columns[1:])]

metadata_V4.to_csv('../Data/multi-omics/16S_V4_metaB-matched.csv', index=0)
metadata_V4

             sample id    group
18    LAMI.RD017.D0.C1  Healthy
22    LAMI.RD017.D0.C2  Healthy
27   LAMI.RD007.D14.C1  Healthy
28   LAMI.RD017.D28.C2  Healthy
33    LAMI.RD004.D0.C1  Healthy
38   LAMI.RD001.D14.C1  Healthy
45   LAMI.RD001.D28.C1  Healthy
46   LAMI.RD017.D28.C1  Healthy
49   LAMI.RD017.D14.C2  Healthy
58   LAMI.RD006.D14.C1  Healthy
64   LAMI.RD007.D14.C2  Healthy
66    LAMI.RD018.D0.C2  Healthy
88   LAMI.RD011.D14.C2  Healthy
114  LAMI.RD007.D28.C1  Healthy
124  LAMI.RD007.D28.C2  Healthy
127   LAMI.RD001.D0.C2  Healthy
151   LAMI.RD018.D0.C1  Healthy
204  LAMI.RD006.D14.C2  Healthy
205  LAMI.RD001.D28.C2  Healthy
209  LAMI.RD004.D28.C2  Healthy
216   LAMI.RD011.D0.C2  Healthy
239   LAMI.RD004.D0.C2  Healthy
255  LAMI.RD011.D14.C1  Healthy
262   LAMI.RD001.D0.C1  Healthy
265  LAMI.RD001.D14.C2  Healthy

In [1117]:
# Save as biom for mmvec
metaB_V4_tbl_transposed = metaB_V4_tbl_relative.T
output_path = f'../Data/multi-omics/metabolomics-tbl_16S_V4-matched_relative_{skin_group}.biom'
save_as_biom(metaB_V4_tbl_transposed, output_path)

In [1118]:
# Save as biom for mmvec
V4_tbl_matched_transposed = V4_tbl_matched_relative.T
output_path = '../Data/multi-omics/16S_V4-tbl_metaB-matched_relative.biom'
save_as_biom(V4_tbl_matched_transposed, output_path)

### Combine V1-V3 and V4 tables

In [1119]:
# Find common rows (samples)
common_rows = V1V3_tbl_matched.index.intersection(V4_tbl_matched.index)

# Subset both DataFrames to keep only common rows
V1V3_tbl_matched = V1V3_tbl_matched.loc[common_rows]
V4_tbl_matched = V4_tbl_matched.loc[common_rows]

# Merge by taking average of values row-wise
merged_tbl = V1V3_tbl_matched.add(V4_tbl_matched, fill_value=0)

# Sort columns by total sum (descending order)
merged_tbl = merged_tbl[merged_tbl.sum().sort_values(ascending=False).index]

merged_tbl

,g__Cutibacterium,g__Staphylococcus,g__Corynebacterium,g__Streptococcus,g__Lawsonella,g__Micrococcus,g__Haemophilus,g__Kocuria,g__Lactobacillus,g__Veillonella,g__Rothia
LAMI.RD001.D0.C1,2363.0,411.0,450.0,706.0,222.0,137.0,562.0,17.0,16.0,76.0,86.0
LAMI.RD001.D0.C2,1811.0,507.0,861.0,742.0,337.0,127.0,538.0,12.0,347.0,73.0,99.0
LAMI.RD001.D14.C1,2234.0,537.0,1407.0,487.0,709.0,123.0,176.0,5.0,177.0,60.0,27.0
LAMI.RD001.D14.C2,1761.0,581.0,1002.0,903.0,357.0,70.0,514.0,11.0,49.0,152.0,78.0
LAMI.RD001.D28.C1,2368.0,698.0,1057.0,642.0,674.0,94.0,152.0,10.0,100.0,84.0,48.0
LAMI.RD001.D28.C2,2292.0,1053.0,1261.0,448.0,913.0,97.0,125.0,14.0,41.0,83.0,45.0
LAMI.RD007.D14.C1,3647.0,2094.0,297.0,183.0,367.0,40.0,78.0,0.0,7.0,74.0,31.0
LAMI.RD007.D14.C2,3598.0,1567.0,379.0,168.0,507.0,63.0,141.0,0.0,0.0,65.0,0.0
LAMI.RD004.D0.C1,2680.0,705.0,1329.0,580.0,70.0,104.0,17.0,5.0,32.0,60.0,59.0
LAMI.RD006.D14.C2,3400.0,774.0,917.0,131.0,416.0,156.0,15.0,33.0,132.0,42.0,3.0
LAMI.RD017.D0.C2,3811.0,1981.0,296.0,96.0,320.0,522.0,94.0,0.0,0.0,24.0,0.0
LAMI.RD004.D0.C2,3038.0,1939.0,1069.0,243.0,126.0,81.0,32.0,18.0,103.0,75.0,57.0
LAMI.RD007.D28.C1,3713.0,2697.0,200.0,186.0,141.0,15.0,93.0,1.0,25.0,12.0,0.0
LAMI.RD006.D14.C1,2693.0,538.0,819.0,765.0,283.0,144.0,7.0,80.0,250.0,64.0,45.0
LAMI.RD007.D28.C2,3721.0,1761.0,551.0,43.0,397.0,15.0,138.0,1.0,30.0,32.0,3.0
LAMI.RD004.D28.C2,1694.0,297.0,1275.0,1501.0,50.0,409.0,44.0,43.0,65.0,159.0,49.0
LAMI.RD017.D28.C2,3869.0,1546.0,195.0,73.0,520.0,602.0,16.0,22.0,8.0,5.0,0.0
LAMI.RD018.D0.C1,3769.0,342.0,617.0,186.0,11.0,404.0,24.0,1055.0,15.0,30.0,16.0
LAMI.RD011.D0.C2,3347.0,2406.0,243.0,181.0,336.0,68.0,228.0,52.0,26.0,34.0,29.0
LAMI.RD018.D0.C2,3711.0,383.0,495.0,582.0,43.0,168.0,86.0,190.0,0.0,113.0,67.0
LAMI.RD011.D14.C2,3500.0,597.0,66.0,16.0,119.0,0.0,2.0,6.0,6.0,9.0,1.0

In [1120]:
V1V3_tbl_matched.columns

Index([' g__Cutibacterium', ' g__Staphylococcus', ' g__Streptococcus',
       ' g__Corynebacterium', ' g__Lawsonella', ' g__Veillonella',
       ' g__Micrococcus', ' g__Lactobacillus', ' g__Rothia', ' g__Haemophilus',
       ' g__Kocuria'],
      dtype='object')

In [1121]:
V4_tbl_matched.columns

Index([' g__Staphylococcus', ' g__Lawsonella', ' g__Corynebacterium',
       ' g__Streptococcus', ' g__Haemophilus', ' g__Micrococcus',
       ' g__Lactobacillus', ' g__Veillonella', ' g__Cutibacterium',
       ' g__Kocuria', ' g__Rothia'],
      dtype='object')

In [1122]:
# Find common rows (samples)
common_rows = V1V3_tbl_matched.index.intersection(V4_tbl_matched.index)

# Subset both DataFrames to keep only common rows
V1V3_tbl_matched = V1V3_tbl_matched.loc[common_rows]
V4_tbl_matched = V4_tbl_matched.loc[common_rows]

# Compute the mean for each matching row and column
merged_tbl = (V1V3_tbl_matched + V4_tbl_matched) / 2

# Sort columns by total mean (descending order)
merged_tbl = merged_tbl[merged_tbl.mean().sort_values(ascending=False).index]

# Display merged DataFrame
merged_tbl

,g__Cutibacterium,g__Staphylococcus,g__Corynebacterium,g__Streptococcus,g__Lawsonella,g__Micrococcus,g__Haemophilus,g__Kocuria,g__Lactobacillus,g__Veillonella,g__Rothia
LAMI.RD001.D0.C1,1181.5,205.5,225.0,353.0,111.0,68.5,281.0,8.5,8.0,38.0,43.0
LAMI.RD001.D0.C2,905.5,253.5,430.5,371.0,168.5,63.5,269.0,6.0,173.5,36.5,49.5
LAMI.RD001.D14.C1,1117.0,268.5,703.5,243.5,354.5,61.5,88.0,2.5,88.5,30.0,13.5
LAMI.RD001.D14.C2,880.5,290.5,501.0,451.5,178.5,35.0,257.0,5.5,24.5,76.0,39.0
LAMI.RD001.D28.C1,1184.0,349.0,528.5,321.0,337.0,47.0,76.0,5.0,50.0,42.0,24.0
LAMI.RD001.D28.C2,1146.0,526.5,630.5,224.0,456.5,48.5,62.5,7.0,20.5,41.5,22.5
LAMI.RD007.D14.C1,1823.5,1047.0,148.5,91.5,183.5,20.0,39.0,0.0,3.5,37.0,15.5
LAMI.RD007.D14.C2,1799.0,783.5,189.5,84.0,253.5,31.5,70.5,0.0,0.0,32.5,0.0
LAMI.RD004.D0.C1,1340.0,352.5,664.5,290.0,35.0,52.0,8.5,2.5,16.0,30.0,29.5
LAMI.RD006.D14.C2,1700.0,387.0,458.5,65.5,208.0,78.0,7.5,16.5,66.0,21.0,1.5
LAMI.RD017.D0.C2,1905.5,990.5,148.0,48.0,160.0,261.0,47.0,0.0,0.0,12.0,0.0
LAMI.RD004.D0.C2,1519.0,969.5,534.5,121.5,63.0,40.5,16.0,9.0,51.5,37.5,28.5
LAMI.RD007.D28.C1,1856.5,1348.5,100.0,93.0,70.5,7.5,46.5,0.5,12.5,6.0,0.0
LAMI.RD006.D14.C1,1346.5,269.0,409.5,382.5,141.5,72.0,3.5,40.0,125.0,32.0,22.5
LAMI.RD007.D28.C2,1860.5,880.5,275.5,21.5,198.5,7.5,69.0,0.5,15.0,16.0,1.5
LAMI.RD004.D28.C2,847.0,148.5,637.5,750.5,25.0,204.5,22.0,21.5,32.5,79.5,24.5
LAMI.RD017.D28.C2,1934.5,773.0,97.5,36.5,260.0,301.0,8.0,11.0,4.0,2.5,0.0
LAMI.RD018.D0.C1,1884.5,171.0,308.5,93.0,5.5,202.0,12.0,527.5,7.5,15.0,8.0
LAMI.RD011.D0.C2,1673.5,1203.0,121.5,90.5,168.0,34.0,114.0,26.0,13.0,17.0,14.5
LAMI.RD018.D0.C2,1855.5,191.5,247.5,291.0,21.5,84.0,43.0,95.0,0.0,56.5,33.5
LAMI.RD011.D14.C2,1750.0,298.5,33.0,8.0,59.5,0.0,1.0,3.0,3.0,4.5,0.5

In [1123]:
# Convert to relative abundance (row-wise normalization)
merged_tbl_relative = merged_tbl.div(merged_tbl.sum(axis=1), axis=0)
merged_tbl_relative

,g__Cutibacterium,g__Staphylococcus,g__Corynebacterium,g__Streptococcus,g__Lawsonella,g__Micrococcus,g__Haemophilus,g__Kocuria,g__Lactobacillus,g__Veillonella,g__Rothia
LAMI.RD001.D0.C1,0.468292,0.081451,0.089180,0.139913,0.043995,0.027150,0.111375,0.003369,0.003171,0.015061,0.017043
LAMI.RD001.D0.C2,0.332050,0.092959,0.157866,0.136047,0.061790,0.023286,0.098643,0.002200,0.063623,0.013385,0.018152
LAMI.RD001.D14.C1,0.375968,0.090374,0.236789,0.081959,0.119320,0.020700,0.029620,0.000841,0.029788,0.010098,0.004544
LAMI.RD001.D14.C2,0.321468,0.106061,0.182913,0.164841,0.065170,0.012778,0.093830,0.002008,0.008945,0.027747,0.014239
LAMI.RD001.D28.C1,0.399528,0.117766,0.178336,0.108318,0.113717,0.015860,0.025645,0.001687,0.016872,0.014172,0.008099
LAMI.RD001.D28.C2,0.359699,0.165254,0.197897,0.070308,0.143283,0.015223,0.019617,0.002197,0.006434,0.013026,0.007062
LAMI.RD007.D14.C1,0.534908,0.307128,0.043561,0.026841,0.053828,0.005867,0.011440,0.000000,0.001027,0.010854,0.004547
LAMI.RD007.D14.C2,0.554562,0.241523,0.058416,0.025894,0.078144,0.009710,0.021732,0.000000,0.000000,0.010018,0.000000
LAMI.RD004.D0.C1,0.475093,0.124978,0.235597,0.102819,0.012409,0.018436,0.003014,0.000886,0.005673,0.010636,0.010459
LAMI.RD006.D14.C2,0.564878,0.128593,0.152351,0.021764,0.069114,0.025918,0.002492,0.005483,0.021931,0.006978,0.000498
LAMI.RD017.D0.C2,0.533455,0.277296,0.041433,0.013438,0.044793,0.073068,0.013158,0.000000,0.000000,0.003359,0.000000
LAMI.RD004.D0.C2,0.448017,0.285946,0.157646,0.035835,0.018581,0.011945,0.004719,0.002654,0.015190,0.011060,0.008406
LAMI.RD007.D28.C1,0.524213,0.380771,0.028237,0.026260,0.019907,0.002118,0.013130,0.000141,0.003530,0.001694,0.000000
LAMI.RD006.D14.C1,0.473453,0.094585,0.143987,0.134494,0.049754,0.025316,0.001231,0.014065,0.043952,0.011252,0.007911
LAMI.RD007.D28.C2,0.556037,0.263150,0.082337,0.006426,0.059325,0.002241,0.020622,0.000149,0.004483,0.004782,0.000448
LAMI.RD004.D28.C2,0.303258,0.053169,0.228249,0.268707,0.008951,0.073219,0.007877,0.007698,0.011636,0.028464,0.008772
LAMI.RD017.D28.C2,0.564323,0.225496,0.028442,0.010648,0.075846,0.087806,0.002334,0.003209,0.001167,0.000729,0.000000
LAMI.RD018.D0.C1,0.582625,0.052868,0.095378,0.028753,0.001700,0.062452,0.003710,0.163085,0.002319,0.004638,0.002473
LAMI.RD011.D0.C2,0.481583,0.346187,0.034964,0.026043,0.048345,0.009784,0.032806,0.007482,0.003741,0.004892,0.004173
LAMI.RD018.D0.C2,0.635663,0.065605,0.084789,0.099692,0.007366,0.028777,0.014731,0.032545,0.000000,0.019356,0.011477
LAMI.RD011.D14.C2,0.809810,0.138130,0.015271,0.003702,0.027534,0.000000,0.000463,0.001388,0.001388,0.002082,0.000231

In [1124]:
merged_tbl_relative.columns

Index([' g__Cutibacterium', ' g__Staphylococcus', ' g__Corynebacterium',
       ' g__Streptococcus', ' g__Lawsonella', ' g__Micrococcus',
       ' g__Haemophilus', ' g__Kocuria', ' g__Lactobacillus',
       ' g__Veillonella', ' g__Rothia'],
      dtype='object')

In [1125]:
# Save as biom for mmvec
merged_tbl_relative_transposed = merged_tbl_relative.T
output_path = f'../Data/multi-omics/16S_MERGED-Avg-tbl_metaB-matched_relative_{skin_group}.biom'
save_as_biom(merged_tbl_relative_transposed, output_path)

In [1126]:
# Subset metaB_tbl rows where sample is in V1V3_tbl
metaB_MERGED_tbl = metaB_tbl[metaB_tbl.index.isin(merged_tbl_relative.index)]

# Remove the 'group' column (only for VIP table)
# metaB_MERGED_tbl = metaB_MERGED_tbl.drop(columns=['group'])
metaB_MERGED_tbl.index.name = None

In [1127]:
# Sort columns by total sum (descending order)
metaB_MERGED_tbl = metaB_MERGED_tbl[metaB_MERGED_tbl.sum().sort_values(ascending=False).index]
metaB_MERGED_tbl

,"DL-Panthenol (mz: 206.1384472, RT: 1.1194918)","Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","Cyclo(his-pro) (mz: 235.1186308, RT: 0.6402779)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)","(Iso)leucine (mz: 276.143683, RT: 0.6789317)",...,"Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","Phenylbenzimidazole sulfonic acid (mz: 275.0481837, RT: 2.761023)","xylometazoline (mz: 245.2008949, RT: 4.3418465)","Nobiletin (mz: 403.138254, RT: 5.258404)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)"
LAMI.RD001.D0.C1,1473068.10,2987383.80,1942604.50,2025607.40,970487.50,567510.06,611709.700,302670.840,125692.3300,62007.1100,...,29574.6480,39859.7580,12406.82600,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD001.D14.C1,504255.75,3269865.80,2762642.00,3296738.00,1496841.80,706262.44,1140515.800,651436.250,0.0000,87564.6100,...,48005.4060,34747.9200,43799.37000,0.000,17267.4320,0.000,0.0000,0.0,0.0,0.0
LAMI.RD001.D14.C2,3137497.20,2047720.40,2397076.20,3165493.20,1258087.60,717058.00,263219.340,218272.830,31278.8980,200700.7500,...,11624.8200,0.0000,9307.76500,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD001.D0.C2,4475920.50,4255321.50,3177169.00,3035873.00,1358777.60,723508.56,944232.100,568705.940,76490.3800,107037.7500,...,24327.7580,23879.5450,22472.37500,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD001.D28.C1,374392.06,5109647.00,3612457.50,3403914.80,1802260.60,1300446.40,269075.660,835043.000,42245.0160,127635.4450,...,38693.2970,51941.2540,88350.94000,36139.850,2983.9258,0.000,0.0000,0.0,0.0,0.0
LAMI.RD001.D28.C2,242698.45,3283120.20,2124453.20,2050733.50,927238.75,508464.70,424329.250,431731.720,18491.5880,69422.5550,...,62305.8670,39545.8050,31103.10500,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD006.D14.C1,17990890.00,2010665.90,1216507.20,873745.75,335306.12,195284.60,7236.388,81698.730,12493.9800,36073.1170,...,0.0000,7931.4785,0.00000,0.000,36492.6170,0.000,0.0000,0.0,0.0,0.0
LAMI.RD006.D14.C2,18368216.00,1987542.20,1573511.80,1288035.90,547077.70,332766.40,15614.556,123767.820,6616.6740,56982.7580,...,12228.7720,25884.8440,4269.93550,11288.382,59558.3240,0.000,0.0000,0.0,0.0,0.0
LAMI.RD004.D28.C2,192005.80,481245.75,550417.06,214140.56,97621.54,66863.65,88451.336,130940.270,0.0000,3837.1455,...,0.0000,0.0000,0.00000,20156.625,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD007.D14.C1,592174.94,1282058.00,1872823.50,1059865.60,472200.03,172225.81,339311.470,74992.780,107611.1200,50051.3500,...,8401.3790,0.0000,6149.22800,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD007.D14.C2,604114.70,1273196.90,2177613.20,1041504.10,431183.03,188882.20,88737.230,56098.430,40483.4570,69813.4800,...,2641.6797,2061.8467,5039.58700,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD011.D0.C2,1166241.40,668784.94,2110005.50,642503.60,289321.38,124100.31,61936.773,48083.355,870889.6000,96827.5700,...,0.0000,0.0000,0.00000,15417.156,0.0000,53299.305,0.0000,0.0,0.0,0.0
LAMI.RD007.D28.C1,329600.88,770451.30,959016.40,645682.70,272316.44,97546.94,885806.000,53169.906,85500.7200,26220.0200,...,0.0000,0.0000,0.00000,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD007.D28.C2,290537.38,1132991.60,1207126.00,902520.06,421043.12,229239.88,344229.940,105762.880,0.0000,33690.0350,...,26086.1800,2022.2802,0.00000,43746.200,2592.6365,0.000,0.0000,0.0,0.0,0.0
LAMI.RD017.D0.C2,375563.88,2532148.50,3219840.50,2193938.80,1083391.00,631929.06,423195.160,430410.340,6515.3213,99376.5160,...,0.0000,11175.1790,0.00000,44098.290,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD011.D14.C2,5918124.00,932846.44,1144307.80,785636.30,305970.00,162636.17,27341.186,121756.734,18367.0210,54152.3480,...,5234.2970,0.0000,1859.16300,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD018.D0.C1,275152.03,1516432.90,1474842.80,1219120.20,455640.47,228105.77,311432.400,129589.090,0.0000,47656.3050,...,7015.3040,8683.7680,11749.36000,0.000,0.0000,0.000,18853.2660,0.0,0.0,0.0
LAMI.RD018.D0.C2,291113.66,468414.00,859649.06,462423.38,197382.80,125504.10,182831.620,60755.043,61282.1000,54494.3670,...,4554.4960,23054.2290,0.00000,0.000,0.0000,0.000,6323.4814,0.0,0.0,0.0
LAMI.RD004.D0.C1,1320976.80,894108.56,1397783.60,476548.60,194716.80,143560.56,296251.340,108514.290,0.0000,45141.2970,...,4558.7500,5832.5950,849.32385,21788.370,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD004.D0.C2,450825.97,931463.80,1478895.00,342188.56,146963.73,84715.22,198821.900,164585.670,26306.1860,32387.8200,...,1233.0264,1353.8542,0.00000,0.000,0.0000,0.000,0.0000,0.0,0.0,0.0
LAMI.RD017.D28.C2,182236.22,3633830.20,3087111.00,3874744.20,1926863.00,1166240.10,368586.700,326206.940,5044.8040,89957.4700,...,4278.8810,3847.5535,33038.36700,22739.346,0.0000,0.000,0.0000,0.0,0.0,0.0

In [1128]:
# Convert to relative abundance (row-wise normalization)
metaB_MERGED_tbl_relative = metaB_MERGED_tbl.div(metaB_MERGED_tbl.sum(axis=1), axis=0)
metaB_MERGED_tbl_relative

,"DL-Panthenol (mz: 206.1384472, RT: 1.1194918)","Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)","Tyrosine (mz: 182.0809391, RT: 0.6720225)","(Iso)leucine (mz: 132.1017009, RT: 0.71511286)","Phenylalanine (mz: 166.086109, RT: 0.9777797)","Tryptophan (mz: 205.0969182, RT: 2.0760007)","C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)","Cyclo(his-pro) (mz: 235.1186308, RT: 0.6402779)","NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)","(Iso)leucine (mz: 276.143683, RT: 0.6789317)",...,"Urocanic acid (mz: 139.0410336, RT: 0.6406374)","Urocanic acid (mz: 139.0587028, RT: 0.6315576)","Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)","Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)","Phenylbenzimidazole sulfonic acid (mz: 275.0481837, RT: 2.761023)","xylometazoline (mz: 245.2008949, RT: 4.3418465)","Nobiletin (mz: 403.138254, RT: 5.258404)","Gln-C14:0 (mz: 357.2754847, RT: 5.845114)","Sinensetin (mz: 373.127569, RT: 5.0247345)","3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)"
LAMI.RD001.D0.C1,0.130990,0.265648,0.172743,0.180123,0.086299,0.050465,0.054395,0.026914,0.011177,0.005514,...,0.002630,0.003544,0.001103,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD001.D14.C1,0.035618,0.230963,0.195136,0.232861,0.105728,0.049886,0.080559,0.046013,0.000000,0.006185,...,0.003391,0.002454,0.003094,0.000000,0.001220,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD001.D14.C2,0.231220,0.150908,0.176654,0.233283,0.092716,0.052844,0.019398,0.016086,0.002305,0.014791,...,0.000857,0.000000,0.000686,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD001.D0.C2,0.236712,0.225045,0.168027,0.160554,0.071860,0.038263,0.049936,0.030076,0.004045,0.005661,...,0.001287,0.001263,0.001188,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD001.D28.C1,0.021648,0.295443,0.208874,0.196816,0.104208,0.075193,0.015558,0.048283,0.002443,0.007380,...,0.002237,0.003003,0.005108,0.002090,0.000173,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD001.D28.C2,0.023498,0.317870,0.205688,0.198551,0.089775,0.049229,0.041083,0.041800,0.001790,0.006721,...,0.006032,0.003829,0.003011,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD006.D14.C1,0.779160,0.087079,0.052685,0.037841,0.014522,0.008457,0.000313,0.003538,0.000541,0.001562,...,0.000000,0.000344,0.000000,0.000000,0.001580,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD006.D14.C2,0.745155,0.080630,0.063834,0.052253,0.022194,0.013500,0.000633,0.005021,0.000268,0.002312,...,0.000496,0.001050,0.000173,0.000458,0.002416,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD004.D28.C2,0.098307,0.246397,0.281812,0.109640,0.049982,0.034234,0.045287,0.067041,0.000000,0.001965,...,0.000000,0.000000,0.000000,0.010320,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD007.D14.C1,0.095579,0.206929,0.302280,0.171066,0.076215,0.027798,0.054766,0.012104,0.017369,0.008078,...,0.001356,0.000000,0.000993,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD007.D14.C2,0.098004,0.206547,0.353268,0.168960,0.069950,0.030642,0.014396,0.009101,0.006568,0.011326,...,0.000429,0.000334,0.000818,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD011.D0.C2,0.186434,0.106911,0.337303,0.102710,0.046251,0.019839,0.009901,0.007687,0.139220,0.015479,...,0.000000,0.000000,0.000000,0.002465,0.000000,0.00852,0.000000,0.0,0.0,0.0
LAMI.RD007.D28.C1,0.077988,0.182298,0.226915,0.152776,0.064433,0.023081,0.209593,0.012581,0.020231,0.006204,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD007.D28.C2,0.059466,0.231895,0.247069,0.184723,0.086177,0.046920,0.070455,0.021647,0.000000,0.006896,...,0.005339,0.000414,0.000000,0.008954,0.000531,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD017.D0.C2,0.033499,0.225856,0.287196,0.195690,0.096634,0.056365,0.037747,0.038391,0.000581,0.008864,...,0.000000,0.000997,0.000000,0.003933,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD011.D14.C2,0.622115,0.098061,0.120290,0.082586,0.032164,0.017096,0.002874,0.012799,0.001931,0.005693,...,0.000550,0.000000,0.000195,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD018.D0.C1,0.045951,0.253247,0.246301,0.203595,0.076093,0.038094,0.052010,0.021642,0.000000,0.007959,...,0.001172,0.001450,0.001962,0.000000,0.000000,0.00000,0.003149,0.0,0.0,0.0
LAMI.RD018.D0.C2,0.100254,0.161313,0.296047,0.159250,0.067975,0.043221,0.062964,0.020923,0.021104,0.018767,...,0.001568,0.007939,0.000000,0.000000,0.000000,0.00000,0.002178,0.0,0.0,0.0
LAMI.RD004.D0.C1,0.262060,0.177376,0.277297,0.094539,0.038629,0.028480,0.058771,0.021527,0.000000,0.008955,...,0.000904,0.001157,0.000168,0.004322,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD004.D0.C2,0.111170,0.229692,0.364684,0.084381,0.036240,0.020890,0.049028,0.040586,0.006487,0.007987,...,0.000304,0.000334,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0
LAMI.RD017.D28.C2,0.012105,0.241377,0.205061,0.257380,0.127992,0.077467,0.024483,0.021668,0.000335,0.005975,...,0.000284,0.000256,0.002195,0.001510,0.000000,0.00000,0.000000,0.0,0.0,0.0

In [1129]:
# Save as biom for mmvec
metaB_MERGED_tbl_relative_transposed = metaB_MERGED_tbl_relative.T
output_path = f'../Data/multi-omics/metaB_MERGED-Avg-tbl_matched_relative_{skin_group}.biom'
save_as_biom(metaB_MERGED_tbl_relative_transposed, output_path)

In [1130]:
metaB_MERGED_tbl_relative.columns

Index(['DL-Panthenol (mz: 206.1384472, RT: 1.1194918)',
       'Pyroglutamic acid (mz: 130.0497016, RT: 0.64796996)',
       'Tyrosine (mz: 182.0809391, RT: 0.6720225)',
       '(Iso)leucine (mz: 132.1017009, RT: 0.71511286)',
       'Phenylalanine (mz: 166.086109, RT: 0.9777797)',
       'Tryptophan (mz: 205.0969182, RT: 2.0760007)',
       'C19H36O4 Fatty alcohol (mz: 311.2573967, RT: 7.4214296)',
       'Cyclo(his-pro) (mz: 235.1186308, RT: 0.6402779)',
       'NCGC00380271-01 (mz: 505.2636006, RT: 3.5891602)',
       '(Iso)leucine (mz: 276.143683, RT: 0.6789317)',
       'Nicotine (mz: 163.1224157, RT: 0.634317)',
       'Uridine (mz: 245.0765944, RT: 0.65536463)',
       'Paracetamol (mz: 152.0704373, RT: 1.6221956)',
       'N-Oleoylethanolamine (mz: 326.3050565, RT: 7.1323557)',
       'Urocanic acid (mz: 139.0410336, RT: 0.6406374)',
       'Urocanic acid (mz: 139.0587028, RT: 0.6315576)',
       'Glutamyltyrosine (mz: 311.1238575, RT: 1.2036344)',
       'Sorbitane Monooleate (mz: 428.3728208, RT: 6.1563983)',
       'Phenylbenzimidazole sulfonic acid (mz: 275.0481837, RT: 2.761023)',
       'xylometazoline (mz: 245.2008949, RT: 4.3418465)',
       'Nobiletin (mz: 403.138254, RT: 5.258404)',
       'Gln-C14:0 (mz: 357.2754847, RT: 5.845114)',
       'Sinensetin (mz: 373.127569, RT: 5.0247345)',
       '3-O-methylated flavonoids (mz: 433.1489336, RT: 5.410203)'],
      dtype='object')