In [38]:
# Import Python packages
import pandas as pd
import numpy as np
import biom
from biom import Table
from biom.util import biom_open
from biom import load_table
import h5py
import qiime2 as q2
from qiime2 import Artifact

In [44]:
def load_biom_table(biom_path):
    # Load BIOM table and convert to a DataFrame
    table = biom.load_table(biom_path)
    df = pd.DataFrame(table.matrix_data.toarray(),
                      index=table.ids(axis='observation'),
                      columns=table.ids(axis='sample'))

    
    return df

In [45]:
def df_to_biom(df, out_biom_path):
    table = Table(
        df.values,
        observation_ids=df.index.astype(str).tolist(),
        sample_ids=df.columns.astype(str).tolist()
    )

    with h5py.File(out_biom_path, "w") as h5f:
        table.to_hdf5(
            h5f,
            generated_by="column intersection filter"
        )

In [46]:
# Import direct tables from Qiita
path_16S_V1V3 = "179426_feature-table_16S_V1V3_rare-11054.biom"
path_16S_V4 = "174951_feature-table_16S_V4_rare-3769.biom"

df_16S_V1V3 = load_biom_table(path_16S_V1V3)
df_16S_V4 = load_biom_table(path_16S_V4)

In [47]:
# Remove any samples that are blanks
df_16S_V1V3 = df_16S_V1V3.loc[
    :, ~df_16S_V1V3.columns.str.contains("BLANK", case=False, na=False)
]

df_16S_V4 = df_16S_V4.loc[
    :, ~df_16S_V4.columns.str.contains("BLANK", case=False, na=False)
]

In [48]:
# View the 16S V1-V3 table from Qiita rarefied to 11064
df_16S_V1V3

,173980.14901.LAMI.RD001.D0.C1,173980.14901.LAMI.RD001.D0.C2,173980.14901.LAMI.RD001.D14.C1,173980.14901.LAMI.RD001.D28.C1,173980.14901.LAMI.RD002.D14.C1,173980.14901.LAMI.RD006.COSM1,173980.14901.LAMI.RD001.D28.C2,173980.14901.LAMI.RD007.D0.C1,173980.14901.LAMI.RD002.D14.C2,173980.14901.LAMI.RD011.D28.C1,...,173980.14901.LAMI.RD318.D28.C2,173980.14901.LAMI.RD319.D21.C1,173980.14901.LAMI.RD319.D28.C3,173980.14901.LAMI.RD319.D21.C2,173980.14901.LAMI.RD319.D7.C3,173980.14901.LAMI.RD318.D28.C3,173980.14901.LAMI.RD319.D14.C1,173980.14901.LAMI.RD319.D14.C2,173980.14901.LAMI.RD319.D9.C1,173980.14901.LAMI.RD319.D9.C2
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAAGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCCCTGCTTGCAGGGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTGATCTGCCCTGCACTTCGGGATAAGCTTGGGAAACTGGGTCTAATACCGGATAG,18.0,76.0,27.0,82.0,6.0,0.0,136.0,0.0,0.0,0.0,...,2.0,0.0,6.0,2.0,0.0,1.0,7.0,1.0,0.0,7.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTTCTCCGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,93.0,138.0,49.0,0.0,2.0,0.0,55.0,7.0,0.0,2.0,...,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGAAGTTTTTCTGGTGCTTGCACTAGAAAAACTTAGCGGCGAACGGGTGAGTAACACGTAAAGAACCTGCCTCATAGACTGGGACAACTATTGGAAACGATAGCTAATACC,66.0,24.0,41.0,46.0,0.0,0.0,36.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCTCCAGCTTGCTGGAGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTAATCTGCCCTGCACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGGAT,241.0,391.0,729.0,601.0,135.0,0.0,1168.0,17.0,90.0,151.0,...,8.0,42.0,88.0,58.0,17.0,8.0,25.0,69.0,103.0,82.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTCTTCTGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,254.0,325.0,41.0,150.0,53.0,0.0,61.0,18.0,64.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGCTGAAGCTTGGTGCTTGCACTGGGTGGATGAGTGGCGAACGGGTGAGTAATACGTGAGTAACCTGCCCTTGACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGG,0.0,30.0,0.0,21.0,1.0,0.0,18.0,0.0,29.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAGGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,41.0,...,2619.0,2895.0,4847.0,3136.0,7981.0,1604.0,4154.0,4016.0,5902.0,4075.0
ATTGAACGCTGGCGGCAGGCTTAACACATGCAAGTCGAACGGTAGCAGGAGAAAGCTTGCTTTCTTGCTGACGAGTGGCGGACGGGTGAGTAATGCTTGGGAATCTGGCTTATGGAGGGGGATAACTACGGGAAACTGTAGCTAATACCG,44.0,60.0,24.0,30.0,0.0,0.0,10.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCCTTACACATGCAAGTCGAACGGTAACAGGTCTTCGGATGCTGACGAGTGGCGAACGGGTGAGTAATACATCGGAACGTGCCCAGTAATGGGGGATAGCTCGGCGAAAGCCGGATTAATACCGCATACGCC,16.0,21.0,4.0,1.0,21.0,0.0,0.0,2.0,40.0,7.0,...,0.0,1.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
# View the 16S V4 table from Qiita rarefied to 3769
df_16S_V4

,173620.14901.LAMI.RD001.D0.C1,173620.14901.LAMI.RD001.D14.C1,173620.14901.LAMI.RD004.D0.C2,173620.14901.LAMI.RD001.D0.C2,173620.14901.LAMI.RD004.D28.C1,173620.14901.LAMI.RD011.D0.C2,173620.14901.LAMI.RD001.D14.C2,173620.14901.LAMI.RD004.D28.C2,173620.14901.LAMI.RD017.D14.C2,173620.14901.LAMI.RD011.D14.C1,...,173620.14901.LAMI.RD319.D16.C1,173620.14901.LAMI.RD318.D16.C1,173620.14901.LAMI.RD319.D25.C2,173620.14901.LAMI.RD318.D18.C1,173620.14901.LAMI.RD318.D4.C2,173620.14901.LAMI.RD319.D16.C2,173620.14901.LAMI.RD319.D28.C1,173620.14901.LAMI.RD318.D9.C2,173620.14901.LAMI.RD319.D28.C2,173620.14901.LAMI.RD319.D2.C1
TACGTAGGGTGCGAGCGTTATCCGGAATTATTGGGCGTAAAGAGCTCGTAGGCGGTTTGTCGCGTCTGCCGTGAAAGTCCGGGGCTTAACTCCGGATCTGCGGTGGGTACGGGCAGACTAGAGTGCAGTAGGGGAGACTGGAATTCCTGG,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGAGCTAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGTCTTTTAAGTCAGAGGTGAAAGCCCGGGGCTCAACCCCGGAATAGCCTTTGAAACTGGAAGACTTGAATCTTGGAGAGGTCAGTGGAATTCCGAG,0.0,1.0,2.0,1.0,1.0,0.0,0.0,9.0,0.0,0.0,...,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0
TACGTAGGGTACTAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCGCGTCTGCTGTGGAAACGTGCCGCTTAACGGTGCGCGTGCAGTGGGTACGGGCGGACTAGAGTGCAGTAGGGGAGTCTGGAATTCCTGG,11.0,123.0,0.0,4.0,5.0,0.0,50.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGCGCGCAGGTGGTTTCTTAAGTCTGATGTGAAATCTCGCGGCTCAACCGCGAGCGGTCATTGGAAACTGGGGAACTTGAGTGCAGAAGAGGATAGTGGAATTCCAAG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGAAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTCGTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTGGCGAGCTAGAGTATGGCAGAGGGTGGTGGAATTTCCTG,0.0,0.0,0.0,0.0,14.0,0.0,0.0,2.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCACGTCGTCTGTGAAATTCCACAGCTTAACTGTGGGCGTGCAGGCGATACGGGCTGACTTGAGTACTGTAGGGGTAACTGGAATTCCTGG,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACAGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTTGTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTGGCAAGCTAGAGTACGGTAGAGGGTGGTGGAATTTCCTG,9.0,11.0,24.0,0.0,2.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTCAATTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGTTGACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATG,19.0,9.0,0.0,14.0,50.0,54.0,30.0,70.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTTAAGTCAGATGTGAAATCCCCGGGCTTAACCTGGGAACTGCATTTGAAACTGGCAGGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGG,0.0,0.0,19.0,0.0,51.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACAGAGGGTGCGAGCGTTAATCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTATTAAGTCGGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTCGATACTGGTGAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0

In [50]:
# Remove the Qiita artifact id prefix so sample ids are aligned between V1-V3 and V4
df_16S_V1V3.columns = df_16S_V1V3.columns.str.replace(
    r"^173980\.14901\.", "", regex=True
)

df_16S_V4.columns = df_16S_V4.columns.str.replace(
    r"^173620\.14901\.", "", regex=True
)

In [51]:
df_16S_V1V3

,LAMI.RD001.D0.C1,LAMI.RD001.D0.C2,LAMI.RD001.D14.C1,LAMI.RD001.D28.C1,LAMI.RD002.D14.C1,LAMI.RD006.COSM1,LAMI.RD001.D28.C2,LAMI.RD007.D0.C1,LAMI.RD002.D14.C2,LAMI.RD011.D28.C1,...,LAMI.RD318.D28.C2,LAMI.RD319.D21.C1,LAMI.RD319.D28.C3,LAMI.RD319.D21.C2,LAMI.RD319.D7.C3,LAMI.RD318.D28.C3,LAMI.RD319.D14.C1,LAMI.RD319.D14.C2,LAMI.RD319.D9.C1,LAMI.RD319.D9.C2
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAAGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCCCTGCTTGCAGGGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTGATCTGCCCTGCACTTCGGGATAAGCTTGGGAAACTGGGTCTAATACCGGATAG,18.0,76.0,27.0,82.0,6.0,0.0,136.0,0.0,0.0,0.0,...,2.0,0.0,6.0,2.0,0.0,1.0,7.0,1.0,0.0,7.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTTCTCCGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,93.0,138.0,49.0,0.0,2.0,0.0,55.0,7.0,0.0,2.0,...,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGAAGTTTTTCTGGTGCTTGCACTAGAAAAACTTAGCGGCGAACGGGTGAGTAACACGTAAAGAACCTGCCTCATAGACTGGGACAACTATTGGAAACGATAGCTAATACC,66.0,24.0,41.0,46.0,0.0,0.0,36.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCTCCAGCTTGCTGGAGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTAATCTGCCCTGCACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGGAT,241.0,391.0,729.0,601.0,135.0,0.0,1168.0,17.0,90.0,151.0,...,8.0,42.0,88.0,58.0,17.0,8.0,25.0,69.0,103.0,82.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTCTTCTGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,254.0,325.0,41.0,150.0,53.0,0.0,61.0,18.0,64.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGCTGAAGCTTGGTGCTTGCACTGGGTGGATGAGTGGCGAACGGGTGAGTAATACGTGAGTAACCTGCCCTTGACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGG,0.0,30.0,0.0,21.0,1.0,0.0,18.0,0.0,29.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAGGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,41.0,...,2619.0,2895.0,4847.0,3136.0,7981.0,1604.0,4154.0,4016.0,5902.0,4075.0
ATTGAACGCTGGCGGCAGGCTTAACACATGCAAGTCGAACGGTAGCAGGAGAAAGCTTGCTTTCTTGCTGACGAGTGGCGGACGGGTGAGTAATGCTTGGGAATCTGGCTTATGGAGGGGGATAACTACGGGAAACTGTAGCTAATACCG,44.0,60.0,24.0,30.0,0.0,0.0,10.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCCTTACACATGCAAGTCGAACGGTAACAGGTCTTCGGATGCTGACGAGTGGCGAACGGGTGAGTAATACATCGGAACGTGCCCAGTAATGGGGGATAGCTCGGCGAAAGCCGGATTAATACCGCATACGCC,16.0,21.0,4.0,1.0,21.0,0.0,0.0,2.0,40.0,7.0,...,0.0,1.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
# Save them as new bioms for downstream use
df_to_biom(df_16S_V1V3, "179426_feature-table_16S_V1V3_rare-11054_sampleIDfixed.biom")
df_to_biom(df_16S_V4,   "174951_feature-table_16S_V4_rare-3769_sampleIDfixed.biom")

In [53]:
# Sanity check the above bioms
path_16S_V1V3_sampleIDfixed = "179426_feature-table_16S_V1V3_rare-11054_sampleIDfixed.biom"
path_16S_V4_sampleIDfixed = "174951_feature-table_16S_V4_rare-3769_sampleIDfixed.biom"

df_16S_V1V3_sampleIDfixed = load_biom_table(path_16S_V1V3_sampleIDfixed)
df_16S_V4_sampleIDfixed = load_biom_table(path_16S_V4_sampleIDfixed)

In [54]:
# View V1-V3
df_16S_V1V3_sampleIDfixed

,LAMI.RD001.D0.C1,LAMI.RD001.D0.C2,LAMI.RD001.D14.C1,LAMI.RD001.D28.C1,LAMI.RD002.D14.C1,LAMI.RD006.COSM1,LAMI.RD001.D28.C2,LAMI.RD007.D0.C1,LAMI.RD002.D14.C2,LAMI.RD011.D28.C1,...,LAMI.RD318.D28.C2,LAMI.RD319.D21.C1,LAMI.RD319.D28.C3,LAMI.RD319.D21.C2,LAMI.RD319.D7.C3,LAMI.RD318.D28.C3,LAMI.RD319.D14.C1,LAMI.RD319.D14.C2,LAMI.RD319.D9.C1,LAMI.RD319.D9.C2
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAAGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCCCTGCTTGCAGGGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTGATCTGCCCTGCACTTCGGGATAAGCTTGGGAAACTGGGTCTAATACCGGATAG,18.0,76.0,27.0,82.0,6.0,0.0,136.0,0.0,0.0,0.0,...,2.0,0.0,6.0,2.0,0.0,1.0,7.0,1.0,0.0,7.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTTCTCCGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,93.0,138.0,49.0,0.0,2.0,0.0,55.0,7.0,0.0,2.0,...,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGAAGTTTTTCTGGTGCTTGCACTAGAAAAACTTAGCGGCGAACGGGTGAGTAACACGTAAAGAACCTGCCTCATAGACTGGGACAACTATTGGAAACGATAGCTAATACC,66.0,24.0,41.0,46.0,0.0,0.0,36.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCTCCAGCTTGCTGGAGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTAATCTGCCCTGCACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGGAT,241.0,391.0,729.0,601.0,135.0,0.0,1168.0,17.0,90.0,151.0,...,8.0,42.0,88.0,58.0,17.0,8.0,25.0,69.0,103.0,82.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTCTTCTGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,254.0,325.0,41.0,150.0,53.0,0.0,61.0,18.0,64.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGCTGAAGCTTGGTGCTTGCACTGGGTGGATGAGTGGCGAACGGGTGAGTAATACGTGAGTAACCTGCCCTTGACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGG,0.0,30.0,0.0,21.0,1.0,0.0,18.0,0.0,29.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAGGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,41.0,...,2619.0,2895.0,4847.0,3136.0,7981.0,1604.0,4154.0,4016.0,5902.0,4075.0
ATTGAACGCTGGCGGCAGGCTTAACACATGCAAGTCGAACGGTAGCAGGAGAAAGCTTGCTTTCTTGCTGACGAGTGGCGGACGGGTGAGTAATGCTTGGGAATCTGGCTTATGGAGGGGGATAACTACGGGAAACTGTAGCTAATACCG,44.0,60.0,24.0,30.0,0.0,0.0,10.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCCTTACACATGCAAGTCGAACGGTAACAGGTCTTCGGATGCTGACGAGTGGCGAACGGGTGAGTAATACATCGGAACGTGCCCAGTAATGGGGGATAGCTCGGCGAAAGCCGGATTAATACCGCATACGCC,16.0,21.0,4.0,1.0,21.0,0.0,0.0,2.0,40.0,7.0,...,0.0,1.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
# View V4
df_16S_V4_sampleIDfixed

,LAMI.RD001.D0.C1,LAMI.RD001.D14.C1,LAMI.RD004.D0.C2,LAMI.RD001.D0.C2,LAMI.RD004.D28.C1,LAMI.RD011.D0.C2,LAMI.RD001.D14.C2,LAMI.RD004.D28.C2,LAMI.RD017.D14.C2,LAMI.RD011.D14.C1,...,LAMI.RD319.D16.C1,LAMI.RD318.D16.C1,LAMI.RD319.D25.C2,LAMI.RD318.D18.C1,LAMI.RD318.D4.C2,LAMI.RD319.D16.C2,LAMI.RD319.D28.C1,LAMI.RD318.D9.C2,LAMI.RD319.D28.C2,LAMI.RD319.D2.C1
TACGTAGGGTGCGAGCGTTATCCGGAATTATTGGGCGTAAAGAGCTCGTAGGCGGTTTGTCGCGTCTGCCGTGAAAGTCCGGGGCTTAACTCCGGATCTGCGGTGGGTACGGGCAGACTAGAGTGCAGTAGGGGAGACTGGAATTCCTGG,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGAGCTAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGTCTTTTAAGTCAGAGGTGAAAGCCCGGGGCTCAACCCCGGAATAGCCTTTGAAACTGGAAGACTTGAATCTTGGAGAGGTCAGTGGAATTCCGAG,0.0,1.0,2.0,1.0,1.0,0.0,0.0,9.0,0.0,0.0,...,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0
TACGTAGGGTACTAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCGCGTCTGCTGTGGAAACGTGCCGCTTAACGGTGCGCGTGCAGTGGGTACGGGCGGACTAGAGTGCAGTAGGGGAGTCTGGAATTCCTGG,11.0,123.0,0.0,4.0,5.0,0.0,50.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGCGCGCAGGTGGTTTCTTAAGTCTGATGTGAAATCTCGCGGCTCAACCGCGAGCGGTCATTGGAAACTGGGGAACTTGAGTGCAGAAGAGGATAGTGGAATTCCAAG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGAAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTCGTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTGGCGAGCTAGAGTATGGCAGAGGGTGGTGGAATTTCCTG,0.0,0.0,0.0,0.0,14.0,0.0,0.0,2.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCACGTCGTCTGTGAAATTCCACAGCTTAACTGTGGGCGTGCAGGCGATACGGGCTGACTTGAGTACTGTAGGGGTAACTGGAATTCCTGG,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACAGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTTGTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTGGCAAGCTAGAGTACGGTAGAGGGTGGTGGAATTTCCTG,9.0,11.0,24.0,0.0,2.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTCAATTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGTTGACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATG,19.0,9.0,0.0,14.0,50.0,54.0,30.0,70.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTTAAGTCAGATGTGAAATCCCCGGGCTTAACCTGGGAACTGCATTTGAAACTGGCAGGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGG,0.0,0.0,19.0,0.0,51.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACAGAGGGTGCGAGCGTTAATCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTATTAAGTCGGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTCGATACTGGTGAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0